// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module hls_snn_izikevich_mul_57s_32ns_88_5_Mul5S_1(clk, ce, a, b, p);
input clk;
input ce;
input[57 - 1 : 0] a; // synthesis attribute keep a "true"
input[32 - 1 : 0] b; // synthesis attribute keep b "true"
output[88 - 1 : 0] p;

reg signed [57 - 1 : 0] a_reg0;
reg [32 - 1 : 0] b_reg0;
wire signed [88 - 1 : 0] tmp_product;
reg signed [88 - 1 : 0] buff0;
reg signed [88 - 1 : 0] buff1;
reg signed [88 - 1 : 0] buff2;

assign p = buff2;
assign tmp_product = a_reg0 * $signed({1'b0, b_reg0});
always @ (posedge clk) begin
    if (ce) begin
        a_reg0 <= a;
        b_reg0 <= b;
        buff0 <= tmp_product;
        buff1 <= buff0;
        buff2 <= buff1;
    end
end
endmodule

`timescale 1 ns / 1 ps
module hls_snn_izikevich_mul_57s_32ns_88_5(
    clk,
    reset,
    ce,
    din0,
    din1,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input clk;
input reset;
input ce;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
output[dout_WIDTH - 1:0] dout;



hls_snn_izikevich_mul_57s_32ns_88_5_Mul5S_1 hls_snn_izikevich_mul_57s_32ns_88_5_Mul5S_1_U(
    .clk( clk ),
    .ce( ce ),
    .a( din0 ),
    .b( din1 ),
    .p( dout ));

endmodule

