// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_snn_izikevich_snn_process_step (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_V_address0,
        p_V_ce0,
        p_V_q0,
        v_V_address0,
        v_V_ce0,
        v_V_we0,
        v_V_d0,
        v_V_q0,
        v_V_address1,
        v_V_ce1,
        v_V_we1,
        v_V_d1,
        u_V_address0,
        u_V_ce0,
        u_V_we0,
        u_V_d0,
        u_V_q0,
        u_V_address1,
        u_V_ce1,
        u_V_we1,
        u_V_d1,
        input_stream0_TDATA,
        input_stream0_TVALID,
        input_stream0_TREADY,
        input_stream0_TLAST,
        input_stream1_TDATA,
        input_stream1_TVALID,
        input_stream1_TREADY,
        input_stream1_TLAST,
        input_stream2_TDATA,
        input_stream2_TVALID,
        input_stream2_TREADY,
        input_stream2_TLAST,
        input_stream3_TDATA,
        input_stream3_TVALID,
        input_stream3_TREADY,
        input_stream3_TLAST,
        firings_mem_V_i,
        firings_mem_V_o,
        firings_mem_V_o_ap_vld,
        neuron_type_mem_V_address0,
        neuron_type_mem_V_ce0,
        neuron_type_mem_V_q0
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 4'b10;
parameter    ap_ST_st8_fsm_2 = 4'b100;
parameter    ap_ST_st9_fsm_3 = 4'b1000;
parameter    ap_true = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv14_0 = 14'b00000000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv14_2710 = 14'b10011100010000;
parameter    ap_const_lv14_1 = 14'b1;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv14_64 = 14'b1100100;
parameter    ap_const_lv7_64 = 7'b1100100;
parameter    ap_const_lv15_5954 = 15'b101100101010100;
parameter    ap_const_lv7_63 = 7'b1100011;
parameter    ap_const_lv32_23000000 = 32'b100011000000000000000000000000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv16_1000 = 16'b1000000000000;
parameter    ap_const_lv28_E66 = 28'b111001100110;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] p_V_address0;
output   p_V_ce0;
input  [0:0] p_V_q0;
output  [13:0] v_V_address0;
output   v_V_ce0;
output   v_V_we0;
output  [31:0] v_V_d0;
input  [31:0] v_V_q0;
output  [13:0] v_V_address1;
output   v_V_ce1;
output   v_V_we1;
output  [31:0] v_V_d1;
output  [13:0] u_V_address0;
output   u_V_ce0;
output   u_V_we0;
output  [31:0] u_V_d0;
input  [31:0] u_V_q0;
output  [13:0] u_V_address1;
output   u_V_ce1;
output   u_V_we1;
output  [31:0] u_V_d1;
input  [63:0] input_stream0_TDATA;
input   input_stream0_TVALID;
output   input_stream0_TREADY;
input  [0:0] input_stream0_TLAST;
input  [63:0] input_stream1_TDATA;
input   input_stream1_TVALID;
output   input_stream1_TREADY;
input  [0:0] input_stream1_TLAST;
input  [63:0] input_stream2_TDATA;
input   input_stream2_TVALID;
output   input_stream2_TREADY;
input  [0:0] input_stream2_TLAST;
input  [63:0] input_stream3_TDATA;
input   input_stream3_TVALID;
output   input_stream3_TREADY;
input  [0:0] input_stream3_TLAST;
input  [9999:0] firings_mem_V_i;
output  [9999:0] firings_mem_V_o;
output   firings_mem_V_o_ap_vld;
output  [6:0] neuron_type_mem_V_address0;
output   neuron_type_mem_V_ce0;
input  [99:0] neuron_type_mem_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_V_ce0;
reg[13:0] v_V_address0;
reg v_V_ce0;
reg v_V_we0;
reg v_V_ce1;
reg v_V_we1;
reg u_V_ce0;
reg u_V_we0;
reg u_V_ce1;
reg u_V_we1;
reg[9999:0] firings_mem_V_o;
reg neuron_type_mem_V_ce0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [13:0] synapse_s_mem_V_address0;
reg    synapse_s_mem_V_ce0;
wire   [15:0] synapse_s_mem_V_q0;
wire   [13:0] synapse_s_mem_V_address1;
reg    synapse_s_mem_V_ce1;
reg    synapse_s_mem_V_we1;
wire   [15:0] synapse_s_mem_V_d1;
reg   [13:0] indvar_flatten_reg_243;
reg   [6:0] l_i_reg_254;
reg   [13:0] x_i_reg_265;
reg   [6:0] xl_i_reg_276;
reg   [13:0] x_1_i_reg_287;
wire   [0:0] exitcond_flatten_fu_440_p2;
reg   [0:0] exitcond_flatten_reg_644;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_111;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it4;
wire   [13:0] indvar_flatten_next_fu_446_p2;
wire   [6:0] xl_i_mid2_fu_470_p3;
reg   [6:0] xl_i_mid2_reg_653;
wire   [6:0] l_i_mid2_fu_486_p3;
reg   [6:0] l_i_mid2_reg_658;
wire   [13:0] x_i_mid2_fu_494_p3;
wire   [6:0] xl_fu_522_p2;
wire   [13:0] tmp_10_i_fu_528_p2;
wire   [13:0] tmp_2_fu_562_p2;
reg   [13:0] tmp_2_reg_691;
reg   [0:0] p_V_load_reg_696;
wire   [0:0] sel_tmp1_i_fu_580_p2;
reg   [0:0] sel_tmp1_i_reg_701;
reg   [0:0] ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it2;
reg   [0:0] ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it3;
reg   [0:0] ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it4;
wire   [0:0] tmp_fu_592_p2;
reg   [0:0] tmp_reg_706;
reg   [13:0] synapse_s_mem_V_addr_reg_711;
reg   [13:0] ap_reg_ppstg_synapse_s_mem_V_addr_reg_711_pp0_it3;
reg   [13:0] ap_reg_ppstg_synapse_s_mem_V_addr_reg_711_pp0_it4;
wire   [0:0] sel_tmp6_i_fu_602_p2;
reg   [0:0] sel_tmp6_i_reg_717;
reg   [0:0] ap_reg_ppstg_sel_tmp6_i_reg_717_pp0_it3;
reg   [0:0] ap_reg_ppstg_sel_tmp6_i_reg_717_pp0_it4;
reg   [15:0] synapse_value_V_reg_722;
reg   [15:0] p_Val2_s_reg_727;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_idle;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_ready;
wire   [6:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_address0;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_ce0;
wire   [99:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_q0;
wire   [13:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address0;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce0;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we0;
wire   [31:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_d0;
wire   [31:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_q0;
wire   [13:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address1;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce1;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we1;
wire   [31:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_d1;
wire   [13:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_address0;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce0;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we0;
wire   [31:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_d0;
wire   [31:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_q0;
wire   [13:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_address1;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce1;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we1;
wire   [31:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_d1;
wire   [63:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TDATA;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TVALID;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TLAST;
wire   [63:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TDATA;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TVALID;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TLAST;
wire   [63:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TDATA;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TVALID;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TLAST;
wire   [63:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TDATA;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TVALID;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TLAST;
wire   [13:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_address0;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_ce0;
wire   [15:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_q0;
wire   [9999:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_i;
wire   [9999:0] grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o;
wire    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o_ap_vld;
reg   [6:0] l_i_phi_fu_258_p4;
reg    grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st8_fsm_2;
reg    ap_sig_bdd_252;
reg    ap_sig_cseq_ST_st9_fsm_3;
reg    ap_sig_bdd_259;
wire   [63:0] tmp_8_i_fu_506_p1;
wire  signed [63:0] tmp_i_fu_517_p1;
wire   [63:0] tmp_2_cast_fu_598_p1;
wire   [0:0] exitcond_i_fu_464_p2;
wire   [13:0] x_dup_fu_458_p2;
wire   [6:0] l_fu_452_p2;
wire   [13:0] x_1_i_mid2_fu_478_p3;
wire   [14:0] x_1_i_cast1_fu_502_p1;
wire   [14:0] tmp_7_i_fu_511_p2;
wire   [6:0] tmp_1_fu_537_p0;
wire   [0:0] tmp_1_i_fu_543_p2;
wire   [13:0] tmp_1_fu_537_p2;
wire   [13:0] tmp_4_i_cast_fu_559_p1;
wire   [0:0] tmp_9_i_fu_568_p2;
wire   [0:0] sel_tmp_i_fu_574_p2;
wire   [0:0] sel_tmp4_i_fu_553_p2;
wire   [0:0] tmp_2_i_fu_548_p2;
wire   [0:0] sel_tmp5_i_fu_586_p2;
wire   [27:0] p_Val2_i_fu_637_p2;
wire   [15:0] p_Val2_2_i_fu_618_p2;
wire   [15:0] sel_tmp2_i_fu_623_p3;
wire   [15:0] p_Val2_i_fu_637_p0;
wire   [12:0] p_Val2_i_fu_637_p1;
reg   [3:0] ap_NS_fsm;
wire   [27:0] p_Val2_i_fu_637_p00;
wire   [13:0] tmp_1_fu_537_p00;


hls_snn_izikevich_snn_process_step_synapse_s_mem_V #(
    .DataWidth( 16 ),
    .AddressRange( 10000 ),
    .AddressWidth( 14 ))
synapse_s_mem_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( synapse_s_mem_V_address0 ),
    .ce0( synapse_s_mem_V_ce0 ),
    .q0( synapse_s_mem_V_q0 ),
    .address1( synapse_s_mem_V_address1 ),
    .ce1( synapse_s_mem_V_ce1 ),
    .we1( synapse_s_mem_V_we1 ),
    .d1( synapse_s_mem_V_d1 )
);

hls_snn_izikevich_snn_get_synaptic_conductances grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start ),
    .ap_done( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done ),
    .ap_idle( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_idle ),
    .ap_ready( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_ready ),
    .neuron_type_V_address0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_address0 ),
    .neuron_type_V_ce0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_ce0 ),
    .neuron_type_V_q0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_q0 ),
    .v_V_address0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address0 ),
    .v_V_ce0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce0 ),
    .v_V_we0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we0 ),
    .v_V_d0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_d0 ),
    .v_V_q0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_q0 ),
    .v_V_address1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address1 ),
    .v_V_ce1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce1 ),
    .v_V_we1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we1 ),
    .v_V_d1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_d1 ),
    .u_V_address0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_address0 ),
    .u_V_ce0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce0 ),
    .u_V_we0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we0 ),
    .u_V_d0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_d0 ),
    .u_V_q0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_q0 ),
    .u_V_address1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_address1 ),
    .u_V_ce1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce1 ),
    .u_V_we1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we1 ),
    .u_V_d1( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_d1 ),
    .input_stream0_TDATA( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TDATA ),
    .input_stream0_TVALID( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TVALID ),
    .input_stream0_TREADY( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TREADY ),
    .input_stream0_TLAST( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TLAST ),
    .input_stream1_TDATA( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TDATA ),
    .input_stream1_TVALID( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TVALID ),
    .input_stream1_TREADY( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TREADY ),
    .input_stream1_TLAST( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TLAST ),
    .input_stream2_TDATA( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TDATA ),
    .input_stream2_TVALID( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TVALID ),
    .input_stream2_TREADY( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TREADY ),
    .input_stream2_TLAST( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TLAST ),
    .input_stream3_TDATA( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TDATA ),
    .input_stream3_TVALID( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TVALID ),
    .input_stream3_TREADY( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TREADY ),
    .input_stream3_TLAST( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TLAST ),
    .synapse_s_mem_V_address0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_address0 ),
    .synapse_s_mem_V_ce0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_ce0 ),
    .synapse_s_mem_V_q0( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_q0 ),
    .firings_mem_V_i( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_i ),
    .firings_mem_V_o( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o ),
    .firings_mem_V_o_ap_vld( grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o_ap_vld )
);

hls_snn_izikevich_mul_mul_16ns_13ns_28_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
hls_snn_izikevich_mul_mul_16ns_13ns_28_1_U63(
    .din0( p_Val2_i_fu_637_p0 ),
    .din1( p_Val2_i_fu_637_p1 ),
    .dout( p_Val2_i_fu_637_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(exitcond_flatten_fu_440_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2)) begin
            grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_ready)) begin
            grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
        indvar_flatten_reg_243 <= indvar_flatten_next_fu_446_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        indvar_flatten_reg_243 <= ap_const_lv14_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_644 == ap_const_lv1_0))) begin
        l_i_reg_254 <= l_i_mid2_reg_658;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        l_i_reg_254 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
        x_1_i_reg_287 <= tmp_10_i_fu_528_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        x_1_i_reg_287 <= ap_const_lv14_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
        x_i_reg_265 <= x_i_mid2_fu_494_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        x_i_reg_265 <= ap_const_lv14_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
        xl_i_reg_276 <= xl_fu_522_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        xl_i_reg_276 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1)) begin
        ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it1 <= exitcond_flatten_reg_644;
        exitcond_flatten_reg_644 <= exitcond_flatten_fu_440_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_true == ap_true)) begin
        ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it2 <= ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it1;
        ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it3 <= ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it2;
        ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it4 <= ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it3;
        ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it2 <= sel_tmp1_i_reg_701;
        ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it3 <= ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it2;
        ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it4 <= ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it3;
        ap_reg_ppstg_sel_tmp6_i_reg_717_pp0_it3 <= sel_tmp6_i_reg_717;
        ap_reg_ppstg_sel_tmp6_i_reg_717_pp0_it4 <= ap_reg_ppstg_sel_tmp6_i_reg_717_pp0_it3;
        ap_reg_ppstg_synapse_s_mem_V_addr_reg_711_pp0_it3 <= synapse_s_mem_V_addr_reg_711;
        ap_reg_ppstg_synapse_s_mem_V_addr_reg_711_pp0_it4 <= ap_reg_ppstg_synapse_s_mem_V_addr_reg_711_pp0_it3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
        l_i_mid2_reg_658 <= l_i_mid2_fu_486_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_644 == ap_const_lv1_0))) begin
        p_V_load_reg_696 <= p_V_q0;
        sel_tmp1_i_reg_701 <= sel_tmp1_i_fu_580_p2;
        tmp_2_reg_691 <= tmp_2_fu_562_p2;
        tmp_reg_706 <= tmp_fu_592_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it3 == ap_const_lv1_0)) begin
        p_Val2_s_reg_727 <= {{p_Val2_i_fu_637_p2[ap_const_lv32_1B : ap_const_lv32_C]}};
    end
end

always @ (posedge ap_clk) begin
    if ((ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it1 == ap_const_lv1_0)) begin
        sel_tmp6_i_reg_717 <= sel_tmp6_i_fu_602_p2;
        synapse_s_mem_V_addr_reg_711 <= tmp_2_cast_fu_598_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & (ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it2 == ap_const_lv1_0))) begin
        synapse_value_V_reg_722 <= synapse_s_mem_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_440_p2 == ap_const_lv1_0))) begin
        xl_i_mid2_reg_653 <= xl_i_mid2_fu_470_p3;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done or ap_sig_cseq_ST_st9_fsm_3) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3) & ~(ap_const_logic_0 == grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done or ap_sig_cseq_ST_st9_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3) & ~(ap_const_logic_0 == grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_111) begin
    if (ap_sig_bdd_111) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_252) begin
    if (ap_sig_bdd_252) begin
        ap_sig_cseq_ST_st8_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_259) begin
    if (ap_sig_bdd_259) begin
        ap_sig_cseq_ST_st9_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_3 = ap_const_logic_0;
    end
end

always @ (firings_mem_V_i or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o_ap_vld or ap_sig_cseq_ST_st8_fsm_2 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2) & (ap_const_logic_1 == grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o_ap_vld)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3) & (ap_const_logic_1 == grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o_ap_vld)))) begin
        firings_mem_V_o = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o;
    end else begin
        firings_mem_V_o = firings_mem_V_i;
    end
end

always @ (l_i_reg_254 or exitcond_flatten_reg_644 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or l_i_mid2_reg_658) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_644 == ap_const_lv1_0))) begin
        l_i_phi_fu_258_p4 = l_i_mid2_reg_658;
    end else begin
        l_i_phi_fu_258_p4 = l_i_reg_254;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_ce0 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        neuron_type_mem_V_ce0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_ce0;
    end else begin
        neuron_type_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        p_V_ce0 = ap_const_logic_1;
    end else begin
        p_V_ce0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_address0 or ap_sig_cseq_ST_st9_fsm_3 or tmp_2_cast_fu_598_p1) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
        synapse_s_mem_V_address0 = tmp_2_cast_fu_598_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        synapse_s_mem_V_address0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_address0;
    end else begin
        synapse_s_mem_V_address0 = 'bx;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_ce0 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
        synapse_s_mem_V_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        synapse_s_mem_V_ce0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_ce0;
    end else begin
        synapse_s_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it5) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) begin
        synapse_s_mem_V_ce1 = ap_const_logic_1;
    end else begin
        synapse_s_mem_V_ce1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it5 or ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it4) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & (ap_reg_ppstg_exitcond_flatten_reg_644_pp0_it4 == ap_const_lv1_0))) begin
        synapse_s_mem_V_we1 = ap_const_logic_1;
    end else begin
        synapse_s_mem_V_we1 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce0 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        u_V_ce0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce0;
    end else begin
        u_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce1 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        u_V_ce1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_ce1;
    end else begin
        u_V_ce1 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we0 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        u_V_we0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we0;
    end else begin
        u_V_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we1 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        u_V_we1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_we1;
    end else begin
        u_V_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address0 or ap_sig_cseq_ST_st9_fsm_3 or tmp_8_i_fu_506_p1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        v_V_address0 = tmp_8_i_fu_506_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        v_V_address0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address0;
    end else begin
        v_V_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce0 or ap_sig_cseq_ST_st9_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        v_V_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        v_V_ce0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce0;
    end else begin
        v_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce1 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        v_V_ce1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_ce1;
    end else begin
        v_V_ce1 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we0 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        v_V_we0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we0;
    end else begin
        v_V_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we1 or ap_sig_cseq_ST_st9_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_3)) begin
        v_V_we1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_we1;
    end else begin
        v_V_we1 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond_flatten_fu_440_p2 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(exitcond_flatten_fu_440_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(exitcond_flatten_fu_440_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_st8_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_2;
            end
        end
        ap_ST_st8_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_3;
        end
        ap_ST_st9_fsm_3 : 
        begin
            if (~(ap_const_logic_0 == grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_3;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_111 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_252 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_259 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign exitcond_flatten_fu_440_p2 = (indvar_flatten_reg_243 == ap_const_lv14_2710? 1'b1: 1'b0);

assign exitcond_i_fu_464_p2 = (xl_i_reg_276 == ap_const_lv7_64? 1'b1: 1'b0);

assign firings_mem_V_o_ap_vld = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_o_ap_vld;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_ap_start_ap_start_reg;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_firings_mem_V_i = firings_mem_V_i;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TDATA = input_stream0_TDATA;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TLAST = input_stream0_TLAST;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TVALID = input_stream0_TVALID;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TDATA = input_stream1_TDATA;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TLAST = input_stream1_TLAST;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TVALID = input_stream1_TVALID;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TDATA = input_stream2_TDATA;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TLAST = input_stream2_TLAST;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TVALID = input_stream2_TVALID;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TDATA = input_stream3_TDATA;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TLAST = input_stream3_TLAST;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TVALID = input_stream3_TVALID;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_q0 = neuron_type_mem_V_q0;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_synapse_s_mem_V_q0 = synapse_s_mem_V_q0;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_q0 = u_V_q0;

assign grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_q0 = v_V_q0;

assign indvar_flatten_next_fu_446_p2 = (indvar_flatten_reg_243 + ap_const_lv14_1);

assign input_stream0_TREADY = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream0_TREADY;

assign input_stream1_TREADY = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream1_TREADY;

assign input_stream2_TREADY = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream2_TREADY;

assign input_stream3_TREADY = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_input_stream3_TREADY;

assign l_fu_452_p2 = (l_i_phi_fu_258_p4 + ap_const_lv7_1);

assign l_i_mid2_fu_486_p3 = ((exitcond_i_fu_464_p2[0:0] === 1'b1) ? l_fu_452_p2 : l_i_phi_fu_258_p4);

assign neuron_type_mem_V_address0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_neuron_type_V_address0;

assign p_V_address0 = tmp_i_fu_517_p1;

assign p_Val2_2_i_fu_618_p2 = (p_Val2_s_reg_727 + ap_const_lv16_1000);

assign p_Val2_i_fu_637_p0 = p_Val2_i_fu_637_p00;

assign p_Val2_i_fu_637_p00 = synapse_value_V_reg_722;

assign p_Val2_i_fu_637_p1 = ap_const_lv28_E66;

assign sel_tmp1_i_fu_580_p2 = (tmp_1_i_fu_543_p2 & sel_tmp_i_fu_574_p2);

assign sel_tmp2_i_fu_623_p3 = ((ap_reg_ppstg_sel_tmp1_i_reg_701_pp0_it4[0:0] === 1'b1) ? p_Val2_2_i_fu_618_p2 : p_Val2_s_reg_727);

assign sel_tmp4_i_fu_553_p2 = (tmp_1_i_fu_543_p2 ^ ap_const_lv1_1);

assign sel_tmp5_i_fu_586_p2 = (tmp_9_i_fu_568_p2 | sel_tmp4_i_fu_553_p2);

assign sel_tmp6_i_fu_602_p2 = (tmp_reg_706 & p_V_load_reg_696);

assign sel_tmp_i_fu_574_p2 = (tmp_9_i_fu_568_p2 ^ ap_const_lv1_1);

assign synapse_s_mem_V_address1 = ap_reg_ppstg_synapse_s_mem_V_addr_reg_711_pp0_it4;

assign synapse_s_mem_V_d1 = ((ap_reg_ppstg_sel_tmp6_i_reg_717_pp0_it4[0:0] === 1'b1) ? p_Val2_2_i_fu_618_p2 : sel_tmp2_i_fu_623_p3);

assign tmp_10_i_fu_528_p2 = (x_1_i_mid2_fu_478_p3 + ap_const_lv14_1);

assign tmp_1_fu_537_p0 = tmp_1_fu_537_p00;

assign tmp_1_fu_537_p00 = l_i_mid2_reg_658;

assign tmp_1_fu_537_p2 = (tmp_1_fu_537_p0 * $signed('h64));

assign tmp_1_i_fu_543_p2 = (l_i_mid2_reg_658 < ap_const_lv7_63? 1'b1: 1'b0);

assign tmp_2_cast_fu_598_p1 = tmp_2_reg_691;

assign tmp_2_fu_562_p2 = (tmp_1_fu_537_p2 + tmp_4_i_cast_fu_559_p1);

assign tmp_2_i_fu_548_p2 = (l_i_mid2_reg_658 == ap_const_lv7_63? 1'b1: 1'b0);

assign tmp_4_i_cast_fu_559_p1 = xl_i_mid2_reg_653;

assign tmp_7_i_fu_511_p2 = ($signed(x_1_i_cast1_fu_502_p1) + $signed(ap_const_lv15_5954));

assign tmp_8_i_fu_506_p1 = x_1_i_mid2_fu_478_p3;

assign tmp_9_i_fu_568_p2 = ($signed(v_V_q0) < $signed(32'b100011000000000000000000000000)? 1'b1: 1'b0);

assign tmp_fu_592_p2 = (tmp_2_i_fu_548_p2 & sel_tmp5_i_fu_586_p2);

assign tmp_i_fu_517_p1 = $signed(tmp_7_i_fu_511_p2);

assign u_V_address0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_address0;

assign u_V_address1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_address1;

assign u_V_d0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_d0;

assign u_V_d1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_u_V_d1;

assign v_V_address1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_address1;

assign v_V_d0 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_d0;

assign v_V_d1 = grp_hls_snn_izikevich_snn_get_synaptic_conductances_fu_298_v_V_d1;

assign x_1_i_cast1_fu_502_p1 = x_1_i_mid2_fu_478_p3;

assign x_1_i_mid2_fu_478_p3 = ((exitcond_i_fu_464_p2[0:0] === 1'b1) ? x_dup_fu_458_p2 : x_1_i_reg_287);

assign x_dup_fu_458_p2 = (x_i_reg_265 + ap_const_lv14_64);

assign x_i_mid2_fu_494_p3 = ((exitcond_i_fu_464_p2[0:0] === 1'b1) ? x_dup_fu_458_p2 : x_i_reg_265);

assign xl_fu_522_p2 = (xl_i_mid2_fu_470_p3 + ap_const_lv7_1);

assign xl_i_mid2_fu_470_p3 = ((exitcond_i_fu_464_p2[0:0] === 1'b1) ? ap_const_lv7_0 : xl_i_reg_276);


endmodule //hls_snn_izikevich_snn_process_step

