// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_snn_izikevich_axis_cp_output_to_stream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TLAST,
        v_V_address0,
        v_V_ce0,
        v_V_q0,
        v_V_address1,
        v_V_ce1,
        v_V_q1,
        output_indexes_mem_address0,
        output_indexes_mem_ce0,
        output_indexes_mem_q0,
        output_indexes_mem_address1,
        output_indexes_mem_ce1,
        output_indexes_mem_q1,
        firings_V_read
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 4'b10;
parameter    ap_ST_pp1_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st14_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv14_0 = 14'b00000000000000;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_E8 = 8'b11101000;
parameter    ap_const_lv8_9D = 8'b10011101;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv14_40 = 14'b1000000;
parameter    ap_const_lv14_1 = 14'b1;
parameter    ap_const_lv14_2710 = 14'b10011100010000;
parameter    ap_const_lv15_1 = 15'b1;
parameter    ap_const_lv15_2710 = 15'b10011100010000;
parameter    ap_const_lv14_3 = 14'b11;
parameter    ap_const_lv15_2 = 15'b10;
parameter    ap_const_lv15_3 = 15'b11;
parameter    ap_const_lv14_7 = 14'b111;
parameter    ap_const_lv15_4 = 15'b100;
parameter    ap_const_lv15_5 = 15'b101;
parameter    ap_const_lv15_6 = 15'b110;
parameter    ap_const_lv15_7 = 15'b111;
parameter    ap_const_lv14_F = 14'b1111;
parameter    ap_const_lv15_8 = 15'b1000;
parameter    ap_const_lv15_9 = 15'b1001;
parameter    ap_const_lv15_A = 15'b1010;
parameter    ap_const_lv15_B = 15'b1011;
parameter    ap_const_lv15_C = 15'b1100;
parameter    ap_const_lv15_D = 15'b1101;
parameter    ap_const_lv15_E = 15'b1110;
parameter    ap_const_lv15_F = 15'b1111;
parameter    ap_const_lv14_1F = 14'b11111;
parameter    ap_const_lv15_10 = 15'b10000;
parameter    ap_const_lv15_11 = 15'b10001;
parameter    ap_const_lv15_12 = 15'b10010;
parameter    ap_const_lv15_13 = 15'b10011;
parameter    ap_const_lv15_14 = 15'b10100;
parameter    ap_const_lv15_15 = 15'b10101;
parameter    ap_const_lv15_16 = 15'b10110;
parameter    ap_const_lv15_17 = 15'b10111;
parameter    ap_const_lv15_18 = 15'b11000;
parameter    ap_const_lv15_19 = 15'b11001;
parameter    ap_const_lv15_1A = 15'b11010;
parameter    ap_const_lv15_1B = 15'b11011;
parameter    ap_const_lv15_1C = 15'b11100;
parameter    ap_const_lv15_1D = 15'b11101;
parameter    ap_const_lv15_1E = 15'b11110;
parameter    ap_const_lv15_1F = 15'b11111;
parameter    ap_const_lv14_3F = 14'b111111;
parameter    ap_const_lv8_9B = 8'b10011011;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [63:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [0:0] output_stream_TLAST;
output  [13:0] v_V_address0;
output   v_V_ce0;
input  [31:0] v_V_q0;
output  [13:0] v_V_address1;
output   v_V_ce1;
input  [31:0] v_V_q1;
output  [7:0] output_indexes_mem_address0;
output   output_indexes_mem_ce0;
input  [31:0] output_indexes_mem_q0;
output  [7:0] output_indexes_mem_address1;
output   output_indexes_mem_ce1;
input  [31:0] output_indexes_mem_q1;
input  [9999:0] firings_V_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] output_stream_TDATA;
reg output_stream_TVALID;
reg[0:0] output_stream_TLAST;
reg v_V_ce0;
reg v_V_ce1;
reg output_indexes_mem_ce0;
reg output_indexes_mem_ce1;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [0:0] stream_id_reg_221;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_58;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it8;
reg    ap_sig_ioackin_output_stream_TREADY;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it2;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it3;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it4;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it5;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it6;
reg   [0:0] ap_reg_ppstg_stream_id_reg_221_pp0_it7;
reg   [1:0] x_reg_234;
reg   [7:0] stream_id_1_reg_245;
reg   [13:0] x_1_reg_256;
wire   [7:0] output_indexes_mem_addr_gep_fu_175_p3;
reg   [7:0] output_indexes_mem_addr_reg_2162;
reg   [0:0] stream_id_phi_fu_225_p4;
wire   [1:0] x_2_fu_278_p2;
reg   [31:0] v_V_load_reg_2187;
wire   [0:0] tmp_83_fu_294_p2;
reg   [0:0] tmp_83_reg_2192;
reg   [0:0] ap_reg_ppstg_tmp_83_reg_2192_pp0_it3;
reg   [0:0] ap_reg_ppstg_tmp_83_reg_2192_pp0_it4;
reg   [0:0] ap_reg_ppstg_tmp_83_reg_2192_pp0_it5;
reg   [0:0] ap_reg_ppstg_tmp_83_reg_2192_pp0_it6;
reg   [0:0] ap_reg_ppstg_tmp_83_reg_2192_pp0_it7;
reg   [0:0] ap_reg_ppstg_tmp_83_reg_2192_pp0_it8;
reg   [31:0] v_V_load_1_reg_2197;
wire   [0:0] tmp_86_fu_300_p2;
reg   [0:0] tmp_86_reg_2202;
reg   [0:0] ap_reg_ppstg_tmp_86_reg_2202_pp0_it3;
reg   [0:0] ap_reg_ppstg_tmp_86_reg_2202_pp0_it4;
reg   [0:0] ap_reg_ppstg_tmp_86_reg_2202_pp0_it5;
reg   [0:0] ap_reg_ppstg_tmp_86_reg_2202_pp0_it6;
reg   [0:0] ap_reg_ppstg_tmp_86_reg_2202_pp0_it7;
reg   [0:0] ap_reg_ppstg_tmp_86_reg_2202_pp0_it8;
wire   [31:0] p_Result_s_fu_326_p5;
reg   [31:0] p_Result_s_reg_2207;
wire   [31:0] p_Result_1_fu_358_p5;
reg   [31:0] p_Result_1_reg_2212;
wire   [0:0] exitcond6_fu_391_p2;
reg   [0:0] exitcond6_reg_2217;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_2;
reg    ap_sig_bdd_183;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [7:0] stream_id_2_fu_397_p2;
wire   [13:0] x_3_fu_403_p2;
wire   [0:0] tmp_fu_413_p3;
reg   [0:0] tmp_reg_2231;
wire   [0:0] tmp_114_1_fu_443_p2;
reg   [0:0] tmp_114_1_reg_2236;
wire   [0:0] tmp_114_2_fu_468_p2;
reg   [0:0] tmp_114_2_reg_2241;
wire   [0:0] tmp_114_3_fu_497_p2;
reg   [0:0] tmp_114_3_reg_2246;
wire   [0:0] tmp_114_4_fu_522_p2;
reg   [0:0] tmp_114_4_reg_2251;
wire   [0:0] tmp_114_5_fu_547_p2;
reg   [0:0] tmp_114_5_reg_2256;
wire   [0:0] tmp_114_6_fu_572_p2;
reg   [0:0] tmp_114_6_reg_2261;
wire   [0:0] tmp_114_7_fu_601_p2;
reg   [0:0] tmp_114_7_reg_2266;
wire   [0:0] tmp_114_8_fu_626_p2;
reg   [0:0] tmp_114_8_reg_2271;
wire   [0:0] tmp_114_9_fu_651_p2;
reg   [0:0] tmp_114_9_reg_2276;
wire   [0:0] tmp_114_s_fu_676_p2;
reg   [0:0] tmp_114_s_reg_2281;
wire   [0:0] tmp_114_10_fu_701_p2;
reg   [0:0] tmp_114_10_reg_2286;
wire   [0:0] tmp_114_11_fu_726_p2;
reg   [0:0] tmp_114_11_reg_2291;
wire   [0:0] tmp_114_12_fu_751_p2;
reg   [0:0] tmp_114_12_reg_2296;
wire   [0:0] tmp_114_13_fu_776_p2;
reg   [0:0] tmp_114_13_reg_2301;
wire   [0:0] tmp_114_14_fu_805_p2;
reg   [0:0] tmp_114_14_reg_2306;
wire   [0:0] tmp_114_15_fu_830_p2;
reg   [0:0] tmp_114_15_reg_2311;
wire   [0:0] tmp_114_16_fu_855_p2;
reg   [0:0] tmp_114_16_reg_2316;
wire   [0:0] tmp_114_17_fu_880_p2;
reg   [0:0] tmp_114_17_reg_2321;
wire   [0:0] tmp_114_18_fu_905_p2;
reg   [0:0] tmp_114_18_reg_2326;
wire   [0:0] tmp_114_19_fu_930_p2;
reg   [0:0] tmp_114_19_reg_2331;
wire   [0:0] tmp_114_20_fu_955_p2;
reg   [0:0] tmp_114_20_reg_2336;
wire   [0:0] tmp_114_21_fu_980_p2;
reg   [0:0] tmp_114_21_reg_2341;
wire   [0:0] tmp_114_22_fu_1005_p2;
reg   [0:0] tmp_114_22_reg_2346;
wire   [0:0] tmp_114_23_fu_1030_p2;
reg   [0:0] tmp_114_23_reg_2351;
wire   [0:0] tmp_114_24_fu_1055_p2;
reg   [0:0] tmp_114_24_reg_2356;
wire   [0:0] tmp_114_25_fu_1080_p2;
reg   [0:0] tmp_114_25_reg_2361;
wire   [0:0] tmp_114_26_fu_1105_p2;
reg   [0:0] tmp_114_26_reg_2366;
wire   [0:0] tmp_114_27_fu_1130_p2;
reg   [0:0] tmp_114_27_reg_2371;
wire   [0:0] tmp_114_28_fu_1155_p2;
reg   [0:0] tmp_114_28_reg_2376;
wire   [0:0] tmp_114_29_fu_1180_p2;
reg   [0:0] tmp_114_29_reg_2381;
wire   [0:0] tmp_114_30_fu_1209_p2;
reg   [0:0] tmp_114_30_reg_2386;
wire   [0:0] tmp_114_31_fu_1234_p2;
reg   [0:0] tmp_114_31_reg_2391;
wire   [0:0] tmp_114_32_fu_1259_p2;
reg   [0:0] tmp_114_32_reg_2396;
wire   [0:0] tmp_114_33_fu_1284_p2;
reg   [0:0] tmp_114_33_reg_2401;
wire   [0:0] tmp_114_34_fu_1309_p2;
reg   [0:0] tmp_114_34_reg_2406;
wire   [0:0] tmp_114_35_fu_1334_p2;
reg   [0:0] tmp_114_35_reg_2411;
wire   [0:0] tmp_114_36_fu_1359_p2;
reg   [0:0] tmp_114_36_reg_2416;
wire   [0:0] tmp_114_37_fu_1384_p2;
reg   [0:0] tmp_114_37_reg_2421;
wire   [0:0] tmp_114_38_fu_1409_p2;
reg   [0:0] tmp_114_38_reg_2426;
wire   [0:0] tmp_114_39_fu_1434_p2;
reg   [0:0] tmp_114_39_reg_2431;
wire   [0:0] tmp_114_40_fu_1459_p2;
reg   [0:0] tmp_114_40_reg_2436;
wire   [0:0] tmp_114_41_fu_1484_p2;
reg   [0:0] tmp_114_41_reg_2441;
wire   [0:0] tmp_114_42_fu_1509_p2;
reg   [0:0] tmp_114_42_reg_2446;
wire   [0:0] tmp_114_43_fu_1534_p2;
reg   [0:0] tmp_114_43_reg_2451;
wire   [0:0] tmp_114_44_fu_1559_p2;
reg   [0:0] tmp_114_44_reg_2456;
wire   [0:0] tmp_114_45_fu_1584_p2;
reg   [0:0] tmp_114_45_reg_2461;
wire   [0:0] tmp_114_46_fu_1609_p2;
reg   [0:0] tmp_114_46_reg_2466;
wire   [0:0] tmp_114_47_fu_1634_p2;
reg   [0:0] tmp_114_47_reg_2471;
wire   [0:0] tmp_114_48_fu_1659_p2;
reg   [0:0] tmp_114_48_reg_2476;
wire   [0:0] tmp_114_49_fu_1684_p2;
reg   [0:0] tmp_114_49_reg_2481;
wire   [0:0] tmp_114_50_fu_1709_p2;
reg   [0:0] tmp_114_50_reg_2486;
wire   [0:0] tmp_114_51_fu_1734_p2;
reg   [0:0] tmp_114_51_reg_2491;
wire   [0:0] tmp_114_52_fu_1759_p2;
reg   [0:0] tmp_114_52_reg_2496;
wire   [0:0] tmp_114_53_fu_1784_p2;
reg   [0:0] tmp_114_53_reg_2501;
wire   [0:0] tmp_114_54_fu_1809_p2;
reg   [0:0] tmp_114_54_reg_2506;
wire   [0:0] tmp_114_55_fu_1834_p2;
reg   [0:0] tmp_114_55_reg_2511;
wire   [0:0] tmp_114_56_fu_1859_p2;
reg   [0:0] tmp_114_56_reg_2516;
wire   [0:0] tmp_114_57_fu_1884_p2;
reg   [0:0] tmp_114_57_reg_2521;
wire   [0:0] tmp_114_58_fu_1909_p2;
reg   [0:0] tmp_114_58_reg_2526;
wire   [0:0] tmp_114_59_fu_1934_p2;
reg   [0:0] tmp_114_59_reg_2531;
wire   [0:0] tmp_114_60_fu_1959_p2;
reg   [0:0] tmp_114_60_reg_2536;
wire   [0:0] tmp_114_61_fu_1984_p2;
reg   [0:0] tmp_114_61_reg_2541;
wire   [0:0] tmp_114_62_fu_2013_p2;
reg   [0:0] tmp_114_62_reg_2546;
wire   [0:0] tmp_last_V_fu_2019_p2;
reg   [0:0] tmp_last_V_reg_2551;
wire   [63:0] tmp_84_fu_273_p1;
wire   [63:0] tmp_82_fu_284_p1;
wire   [63:0] tmp_85_fu_289_p1;
wire   [63:0] c_fu_382_p3;
wire   [63:0] tmp_data_4_fu_2025_p65;
reg    ap_reg_ioackin_output_stream_TREADY = 1'b0;
wire   [31:0] grp_fu_267_p1;
wire   [31:0] res_V_3_fu_306_p1;
wire   [7:0] exp_V_fu_310_p4;
wire   [7:0] exp_V_4_fu_320_p2;
wire   [31:0] grp_fu_270_p1;
wire   [31:0] res_V_4_fu_338_p1;
wire   [7:0] exp_V_2_fu_342_p4;
wire   [7:0] exp_V_5_fu_352_p2;
wire   [31:0] tmp_i_56_fu_376_p3;
wire   [31:0] tmp_i_fu_370_p3;
wire   [14:0] tmp_88_fu_409_p1;
wire   [13:0] tmp_115_s_fu_420_p2;
wire   [14:0] tmp_115_cast5_fu_426_p1;
wire   [0:0] tmp_112_1_fu_430_p2;
wire   [0:0] tmp_92_fu_436_p3;
wire   [14:0] tmp_115_1_fu_449_p2;
wire   [0:0] tmp_112_2_fu_455_p2;
wire   [0:0] tmp_93_fu_461_p3;
wire   [13:0] tmp_115_2_fu_474_p2;
wire   [14:0] tmp_115_2_cast4_fu_480_p1;
wire   [0:0] tmp_112_3_fu_484_p2;
wire   [0:0] tmp_94_fu_490_p3;
wire   [14:0] tmp_115_3_fu_503_p2;
wire   [0:0] tmp_112_4_fu_509_p2;
wire   [0:0] tmp_95_fu_515_p3;
wire   [14:0] tmp_115_4_fu_528_p2;
wire   [0:0] tmp_112_5_fu_534_p2;
wire   [0:0] tmp_96_fu_540_p3;
wire   [14:0] tmp_115_5_fu_553_p2;
wire   [0:0] tmp_112_6_fu_559_p2;
wire   [0:0] tmp_97_fu_565_p3;
wire   [13:0] tmp_115_6_fu_578_p2;
wire   [14:0] tmp_115_6_cast3_fu_584_p1;
wire   [0:0] tmp_112_7_fu_588_p2;
wire   [0:0] tmp_98_fu_594_p3;
wire   [14:0] tmp_115_7_fu_607_p2;
wire   [0:0] tmp_112_8_fu_613_p2;
wire   [0:0] tmp_99_fu_619_p3;
wire   [14:0] tmp_115_8_fu_632_p2;
wire   [0:0] tmp_112_9_fu_638_p2;
wire   [0:0] tmp_100_fu_644_p3;
wire   [14:0] tmp_115_9_fu_657_p2;
wire   [0:0] tmp_112_s_fu_663_p2;
wire   [0:0] tmp_101_fu_669_p3;
wire   [14:0] tmp_115_10_fu_682_p2;
wire   [0:0] tmp_112_10_fu_688_p2;
wire   [0:0] tmp_102_fu_694_p3;
wire   [14:0] tmp_115_11_fu_707_p2;
wire   [0:0] tmp_112_11_fu_713_p2;
wire   [0:0] tmp_103_fu_719_p3;
wire   [14:0] tmp_115_12_fu_732_p2;
wire   [0:0] tmp_112_12_fu_738_p2;
wire   [0:0] tmp_104_fu_744_p3;
wire   [14:0] tmp_115_13_fu_757_p2;
wire   [0:0] tmp_112_13_fu_763_p2;
wire   [0:0] tmp_105_fu_769_p3;
wire   [13:0] tmp_115_14_fu_782_p2;
wire   [14:0] tmp_115_14_cast2_fu_788_p1;
wire   [0:0] tmp_112_14_fu_792_p2;
wire   [0:0] tmp_106_fu_798_p3;
wire   [14:0] tmp_115_15_fu_811_p2;
wire   [0:0] tmp_112_15_fu_817_p2;
wire   [0:0] tmp_107_fu_823_p3;
wire   [14:0] tmp_115_16_fu_836_p2;
wire   [0:0] tmp_112_16_fu_842_p2;
wire   [0:0] tmp_108_fu_848_p3;
wire   [14:0] tmp_115_17_fu_861_p2;
wire   [0:0] tmp_112_17_fu_867_p2;
wire   [0:0] tmp_109_fu_873_p3;
wire   [14:0] tmp_115_18_fu_886_p2;
wire   [0:0] tmp_112_18_fu_892_p2;
wire   [0:0] tmp_110_fu_898_p3;
wire   [14:0] tmp_115_19_fu_911_p2;
wire   [0:0] tmp_112_19_fu_917_p2;
wire   [0:0] tmp_111_fu_923_p3;
wire   [14:0] tmp_115_20_fu_936_p2;
wire   [0:0] tmp_112_20_fu_942_p2;
wire   [0:0] tmp_112_fu_948_p3;
wire   [14:0] tmp_115_21_fu_961_p2;
wire   [0:0] tmp_112_21_fu_967_p2;
wire   [0:0] tmp_113_fu_973_p3;
wire   [14:0] tmp_115_22_fu_986_p2;
wire   [0:0] tmp_112_22_fu_992_p2;
wire   [0:0] tmp_114_fu_998_p3;
wire   [14:0] tmp_115_23_fu_1011_p2;
wire   [0:0] tmp_112_23_fu_1017_p2;
wire   [0:0] tmp_115_fu_1023_p3;
wire   [14:0] tmp_115_24_fu_1036_p2;
wire   [0:0] tmp_112_24_fu_1042_p2;
wire   [0:0] tmp_116_fu_1048_p3;
wire   [14:0] tmp_115_25_fu_1061_p2;
wire   [0:0] tmp_112_25_fu_1067_p2;
wire   [0:0] tmp_117_fu_1073_p3;
wire   [14:0] tmp_115_26_fu_1086_p2;
wire   [0:0] tmp_112_26_fu_1092_p2;
wire   [0:0] tmp_118_fu_1098_p3;
wire   [14:0] tmp_115_27_fu_1111_p2;
wire   [0:0] tmp_112_27_fu_1117_p2;
wire   [0:0] tmp_119_fu_1123_p3;
wire   [14:0] tmp_115_28_fu_1136_p2;
wire   [0:0] tmp_112_28_fu_1142_p2;
wire   [0:0] tmp_120_fu_1148_p3;
wire   [14:0] tmp_115_29_fu_1161_p2;
wire   [0:0] tmp_112_29_fu_1167_p2;
wire   [0:0] tmp_121_fu_1173_p3;
wire   [13:0] tmp_115_30_fu_1186_p2;
wire   [14:0] tmp_115_30_cast1_fu_1192_p1;
wire   [0:0] tmp_112_30_fu_1196_p2;
wire   [0:0] tmp_122_fu_1202_p3;
wire   [14:0] tmp_115_31_fu_1215_p2;
wire   [0:0] tmp_112_31_fu_1221_p2;
wire   [0:0] tmp_123_fu_1227_p3;
wire   [14:0] tmp_115_32_fu_1240_p2;
wire   [0:0] tmp_112_32_fu_1246_p2;
wire   [0:0] tmp_124_fu_1252_p3;
wire   [14:0] tmp_115_33_fu_1265_p2;
wire   [0:0] tmp_112_33_fu_1271_p2;
wire   [0:0] tmp_125_fu_1277_p3;
wire   [14:0] tmp_115_34_fu_1290_p2;
wire   [0:0] tmp_112_34_fu_1296_p2;
wire   [0:0] tmp_126_fu_1302_p3;
wire   [14:0] tmp_115_35_fu_1315_p2;
wire   [0:0] tmp_112_35_fu_1321_p2;
wire   [0:0] tmp_127_fu_1327_p3;
wire   [14:0] tmp_115_36_fu_1340_p2;
wire   [0:0] tmp_112_36_fu_1346_p2;
wire   [0:0] tmp_128_fu_1352_p3;
wire   [14:0] tmp_115_37_fu_1365_p2;
wire   [0:0] tmp_112_37_fu_1371_p2;
wire   [0:0] tmp_129_fu_1377_p3;
wire   [14:0] tmp_115_38_fu_1390_p2;
wire   [0:0] tmp_112_38_fu_1396_p2;
wire   [0:0] tmp_130_fu_1402_p3;
wire   [14:0] tmp_115_39_fu_1415_p2;
wire   [0:0] tmp_112_39_fu_1421_p2;
wire   [0:0] tmp_131_fu_1427_p3;
wire   [14:0] tmp_115_40_fu_1440_p2;
wire   [0:0] tmp_112_40_fu_1446_p2;
wire   [0:0] tmp_132_fu_1452_p3;
wire   [14:0] tmp_115_41_fu_1465_p2;
wire   [0:0] tmp_112_41_fu_1471_p2;
wire   [0:0] tmp_133_fu_1477_p3;
wire   [14:0] tmp_115_42_fu_1490_p2;
wire   [0:0] tmp_112_42_fu_1496_p2;
wire   [0:0] tmp_134_fu_1502_p3;
wire   [14:0] tmp_115_43_fu_1515_p2;
wire   [0:0] tmp_112_43_fu_1521_p2;
wire   [0:0] tmp_135_fu_1527_p3;
wire   [14:0] tmp_115_44_fu_1540_p2;
wire   [0:0] tmp_112_44_fu_1546_p2;
wire   [0:0] tmp_136_fu_1552_p3;
wire   [14:0] tmp_115_45_fu_1565_p2;
wire   [0:0] tmp_112_45_fu_1571_p2;
wire   [0:0] tmp_137_fu_1577_p3;
wire   [14:0] tmp_115_46_fu_1590_p2;
wire   [0:0] tmp_112_46_fu_1596_p2;
wire   [0:0] tmp_138_fu_1602_p3;
wire   [14:0] tmp_115_47_fu_1615_p2;
wire   [0:0] tmp_112_47_fu_1621_p2;
wire   [0:0] tmp_139_fu_1627_p3;
wire   [14:0] tmp_115_48_fu_1640_p2;
wire   [0:0] tmp_112_48_fu_1646_p2;
wire   [0:0] tmp_140_fu_1652_p3;
wire   [14:0] tmp_115_49_fu_1665_p2;
wire   [0:0] tmp_112_49_fu_1671_p2;
wire   [0:0] tmp_141_fu_1677_p3;
wire   [14:0] tmp_115_50_fu_1690_p2;
wire   [0:0] tmp_112_50_fu_1696_p2;
wire   [0:0] tmp_142_fu_1702_p3;
wire   [14:0] tmp_115_51_fu_1715_p2;
wire   [0:0] tmp_112_51_fu_1721_p2;
wire   [0:0] tmp_143_fu_1727_p3;
wire   [14:0] tmp_115_52_fu_1740_p2;
wire   [0:0] tmp_112_52_fu_1746_p2;
wire   [0:0] tmp_144_fu_1752_p3;
wire   [14:0] tmp_115_53_fu_1765_p2;
wire   [0:0] tmp_112_53_fu_1771_p2;
wire   [0:0] tmp_145_fu_1777_p3;
wire   [14:0] tmp_115_54_fu_1790_p2;
wire   [0:0] tmp_112_54_fu_1796_p2;
wire   [0:0] tmp_146_fu_1802_p3;
wire   [14:0] tmp_115_55_fu_1815_p2;
wire   [0:0] tmp_112_55_fu_1821_p2;
wire   [0:0] tmp_147_fu_1827_p3;
wire   [14:0] tmp_115_56_fu_1840_p2;
wire   [0:0] tmp_112_56_fu_1846_p2;
wire   [0:0] tmp_148_fu_1852_p3;
wire   [14:0] tmp_115_57_fu_1865_p2;
wire   [0:0] tmp_112_57_fu_1871_p2;
wire   [0:0] tmp_149_fu_1877_p3;
wire   [14:0] tmp_115_58_fu_1890_p2;
wire   [0:0] tmp_112_58_fu_1896_p2;
wire   [0:0] tmp_150_fu_1902_p3;
wire   [14:0] tmp_115_59_fu_1915_p2;
wire   [0:0] tmp_112_59_fu_1921_p2;
wire   [0:0] tmp_151_fu_1927_p3;
wire   [14:0] tmp_115_60_fu_1940_p2;
wire   [0:0] tmp_112_60_fu_1946_p2;
wire   [0:0] tmp_153_fu_1952_p3;
wire   [14:0] tmp_115_61_fu_1965_p2;
wire   [0:0] tmp_112_61_fu_1971_p2;
wire   [0:0] tmp_154_fu_1977_p3;
wire   [13:0] tmp_115_62_fu_1990_p2;
wire   [14:0] tmp_89_fu_2002_p1;
wire   [0:0] tmp_112_62_fu_1996_p2;
wire   [0:0] tmp_155_fu_2006_p3;
reg    grp_fu_267_ce;
reg    grp_fu_270_ce;
reg    ap_sig_cseq_ST_st14_fsm_3;
reg    ap_sig_bdd_1648;
reg   [3:0] ap_NS_fsm;


hls_snn_izikevich_sitofp_32ns_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
hls_snn_izikevich_sitofp_32ns_32_6_U92(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( v_V_load_reg_2187 ),
    .ce( grp_fu_267_ce ),
    .dout( grp_fu_267_p1 )
);

hls_snn_izikevich_sitofp_32ns_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
hls_snn_izikevich_sitofp_32ns_32_6_U93(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( v_V_load_1_reg_2197 ),
    .ce( grp_fu_270_ce ),
    .dout( grp_fu_270_p1 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_output_stream_TREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_output_stream_TREADY <= ap_const_logic_0;
    end else begin
        if (((~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ioackin_output_stream_TREADY <= ap_const_logic_0;
        end else if (((~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_1 == output_stream_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == output_stream_TREADY)))) begin
            ap_reg_ioackin_output_stream_TREADY <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_const_lv1_0 == stream_id_phi_fu_225_p4))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond6_fu_391_p2)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4))) begin
        stream_id_1_reg_245 <= ap_const_lv8_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
        stream_id_1_reg_245 <= stream_id_2_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(stream_id_reg_221 == ap_const_lv1_0))) begin
        stream_id_reg_221 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        stream_id_reg_221 <= ap_const_lv1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4))) begin
        x_1_reg_256 <= ap_const_lv14_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
        x_1_reg_256 <= x_3_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_const_lv1_0 == stream_id_phi_fu_225_p4))) begin
        x_reg_234 <= x_2_fu_278_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        x_reg_234 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        ap_reg_ppstg_stream_id_reg_221_pp0_it1 <= stream_id_reg_221;
    end
end

always @ (posedge ap_clk) begin
    if (~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
        ap_reg_ppstg_stream_id_reg_221_pp0_it2 <= ap_reg_ppstg_stream_id_reg_221_pp0_it1;
        ap_reg_ppstg_stream_id_reg_221_pp0_it3 <= ap_reg_ppstg_stream_id_reg_221_pp0_it2;
        ap_reg_ppstg_stream_id_reg_221_pp0_it4 <= ap_reg_ppstg_stream_id_reg_221_pp0_it3;
        ap_reg_ppstg_stream_id_reg_221_pp0_it5 <= ap_reg_ppstg_stream_id_reg_221_pp0_it4;
        ap_reg_ppstg_stream_id_reg_221_pp0_it6 <= ap_reg_ppstg_stream_id_reg_221_pp0_it5;
        ap_reg_ppstg_stream_id_reg_221_pp0_it7 <= ap_reg_ppstg_stream_id_reg_221_pp0_it6;
        ap_reg_ppstg_stream_id_reg_221_pp0_it8 <= ap_reg_ppstg_stream_id_reg_221_pp0_it7;
        ap_reg_ppstg_tmp_83_reg_2192_pp0_it3 <= tmp_83_reg_2192;
        ap_reg_ppstg_tmp_83_reg_2192_pp0_it4 <= ap_reg_ppstg_tmp_83_reg_2192_pp0_it3;
        ap_reg_ppstg_tmp_83_reg_2192_pp0_it5 <= ap_reg_ppstg_tmp_83_reg_2192_pp0_it4;
        ap_reg_ppstg_tmp_83_reg_2192_pp0_it6 <= ap_reg_ppstg_tmp_83_reg_2192_pp0_it5;
        ap_reg_ppstg_tmp_83_reg_2192_pp0_it7 <= ap_reg_ppstg_tmp_83_reg_2192_pp0_it6;
        ap_reg_ppstg_tmp_83_reg_2192_pp0_it8 <= ap_reg_ppstg_tmp_83_reg_2192_pp0_it7;
        ap_reg_ppstg_tmp_86_reg_2202_pp0_it3 <= tmp_86_reg_2202;
        ap_reg_ppstg_tmp_86_reg_2202_pp0_it4 <= ap_reg_ppstg_tmp_86_reg_2202_pp0_it3;
        ap_reg_ppstg_tmp_86_reg_2202_pp0_it5 <= ap_reg_ppstg_tmp_86_reg_2202_pp0_it4;
        ap_reg_ppstg_tmp_86_reg_2202_pp0_it6 <= ap_reg_ppstg_tmp_86_reg_2202_pp0_it5;
        ap_reg_ppstg_tmp_86_reg_2202_pp0_it7 <= ap_reg_ppstg_tmp_86_reg_2202_pp0_it6;
        ap_reg_ppstg_tmp_86_reg_2202_pp0_it8 <= ap_reg_ppstg_tmp_86_reg_2202_pp0_it7;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        exitcond6_reg_2217 <= exitcond6_fu_391_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_const_lv1_0 == ap_reg_ppstg_stream_id_reg_221_pp0_it7) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_86_reg_2202_pp0_it7))) begin
        p_Result_1_reg_2212 <= p_Result_1_fu_358_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_const_lv1_0 == ap_reg_ppstg_stream_id_reg_221_pp0_it7) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_83_reg_2192_pp0_it7))) begin
        p_Result_s_reg_2207 <= p_Result_s_fu_326_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
        tmp_114_10_reg_2286 <= tmp_114_10_fu_701_p2;
        tmp_114_11_reg_2291 <= tmp_114_11_fu_726_p2;
        tmp_114_12_reg_2296 <= tmp_114_12_fu_751_p2;
        tmp_114_13_reg_2301 <= tmp_114_13_fu_776_p2;
        tmp_114_14_reg_2306 <= tmp_114_14_fu_805_p2;
        tmp_114_15_reg_2311 <= tmp_114_15_fu_830_p2;
        tmp_114_16_reg_2316 <= tmp_114_16_fu_855_p2;
        tmp_114_17_reg_2321 <= tmp_114_17_fu_880_p2;
        tmp_114_18_reg_2326 <= tmp_114_18_fu_905_p2;
        tmp_114_19_reg_2331 <= tmp_114_19_fu_930_p2;
        tmp_114_1_reg_2236 <= tmp_114_1_fu_443_p2;
        tmp_114_20_reg_2336 <= tmp_114_20_fu_955_p2;
        tmp_114_21_reg_2341 <= tmp_114_21_fu_980_p2;
        tmp_114_22_reg_2346 <= tmp_114_22_fu_1005_p2;
        tmp_114_23_reg_2351 <= tmp_114_23_fu_1030_p2;
        tmp_114_24_reg_2356 <= tmp_114_24_fu_1055_p2;
        tmp_114_25_reg_2361 <= tmp_114_25_fu_1080_p2;
        tmp_114_26_reg_2366 <= tmp_114_26_fu_1105_p2;
        tmp_114_27_reg_2371 <= tmp_114_27_fu_1130_p2;
        tmp_114_28_reg_2376 <= tmp_114_28_fu_1155_p2;
        tmp_114_29_reg_2381 <= tmp_114_29_fu_1180_p2;
        tmp_114_2_reg_2241 <= tmp_114_2_fu_468_p2;
        tmp_114_30_reg_2386 <= tmp_114_30_fu_1209_p2;
        tmp_114_31_reg_2391 <= tmp_114_31_fu_1234_p2;
        tmp_114_32_reg_2396 <= tmp_114_32_fu_1259_p2;
        tmp_114_33_reg_2401 <= tmp_114_33_fu_1284_p2;
        tmp_114_34_reg_2406 <= tmp_114_34_fu_1309_p2;
        tmp_114_35_reg_2411 <= tmp_114_35_fu_1334_p2;
        tmp_114_36_reg_2416 <= tmp_114_36_fu_1359_p2;
        tmp_114_37_reg_2421 <= tmp_114_37_fu_1384_p2;
        tmp_114_38_reg_2426 <= tmp_114_38_fu_1409_p2;
        tmp_114_39_reg_2431 <= tmp_114_39_fu_1434_p2;
        tmp_114_3_reg_2246 <= tmp_114_3_fu_497_p2;
        tmp_114_40_reg_2436 <= tmp_114_40_fu_1459_p2;
        tmp_114_41_reg_2441 <= tmp_114_41_fu_1484_p2;
        tmp_114_42_reg_2446 <= tmp_114_42_fu_1509_p2;
        tmp_114_43_reg_2451 <= tmp_114_43_fu_1534_p2;
        tmp_114_44_reg_2456 <= tmp_114_44_fu_1559_p2;
        tmp_114_45_reg_2461 <= tmp_114_45_fu_1584_p2;
        tmp_114_46_reg_2466 <= tmp_114_46_fu_1609_p2;
        tmp_114_47_reg_2471 <= tmp_114_47_fu_1634_p2;
        tmp_114_48_reg_2476 <= tmp_114_48_fu_1659_p2;
        tmp_114_49_reg_2481 <= tmp_114_49_fu_1684_p2;
        tmp_114_4_reg_2251 <= tmp_114_4_fu_522_p2;
        tmp_114_50_reg_2486 <= tmp_114_50_fu_1709_p2;
        tmp_114_51_reg_2491 <= tmp_114_51_fu_1734_p2;
        tmp_114_52_reg_2496 <= tmp_114_52_fu_1759_p2;
        tmp_114_53_reg_2501 <= tmp_114_53_fu_1784_p2;
        tmp_114_54_reg_2506 <= tmp_114_54_fu_1809_p2;
        tmp_114_55_reg_2511 <= tmp_114_55_fu_1834_p2;
        tmp_114_56_reg_2516 <= tmp_114_56_fu_1859_p2;
        tmp_114_57_reg_2521 <= tmp_114_57_fu_1884_p2;
        tmp_114_58_reg_2526 <= tmp_114_58_fu_1909_p2;
        tmp_114_59_reg_2531 <= tmp_114_59_fu_1934_p2;
        tmp_114_5_reg_2256 <= tmp_114_5_fu_547_p2;
        tmp_114_60_reg_2536 <= tmp_114_60_fu_1959_p2;
        tmp_114_61_reg_2541 <= tmp_114_61_fu_1984_p2;
        tmp_114_62_reg_2546 <= tmp_114_62_fu_2013_p2;
        tmp_114_6_reg_2261 <= tmp_114_6_fu_572_p2;
        tmp_114_7_reg_2266 <= tmp_114_7_fu_601_p2;
        tmp_114_8_reg_2271 <= tmp_114_8_fu_626_p2;
        tmp_114_9_reg_2276 <= tmp_114_9_fu_651_p2;
        tmp_114_s_reg_2281 <= tmp_114_s_fu_676_p2;
        tmp_last_V_reg_2551 <= tmp_last_V_fu_2019_p2;
        tmp_reg_2231 <= tmp_fu_413_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_reg_ppstg_stream_id_reg_221_pp0_it1 == ap_const_lv1_0))) begin
        tmp_83_reg_2192 <= tmp_83_fu_294_p2;
        tmp_86_reg_2202 <= tmp_86_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_reg_ppstg_stream_id_reg_221_pp0_it1 == ap_const_lv1_0))) begin
        v_V_load_1_reg_2197 <= v_V_q1;
        v_V_load_reg_2187 <= v_V_q0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st14_fsm_3) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_3))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st14_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_3)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_58) begin
    if (ap_sig_bdd_58) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_183) begin
    if (ap_sig_bdd_183) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_1648) begin
    if (ap_sig_bdd_1648) begin
        ap_sig_cseq_ST_st14_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (output_stream_TREADY or ap_reg_ioackin_output_stream_TREADY) begin
    if ((ap_const_logic_0 == ap_reg_ioackin_output_stream_TREADY)) begin
        ap_sig_ioackin_output_stream_TREADY = output_stream_TREADY;
    end else begin
        ap_sig_ioackin_output_stream_TREADY = ap_const_logic_1;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        grp_fu_267_ce = ap_const_logic_1;
    end else begin
        grp_fu_267_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        grp_fu_270_ce = ap_const_logic_1;
    end else begin
        grp_fu_270_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        output_indexes_mem_ce0 = ap_const_logic_1;
    end else begin
        output_indexes_mem_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        output_indexes_mem_ce1 = ap_const_logic_1;
    end else begin
        output_indexes_mem_ce1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_reg_ppiten_pp0_it9 or exitcond6_reg_2217 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or c_fu_382_p3 or tmp_data_4_fu_2025_p65) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        output_stream_TDATA = tmp_data_4_fu_2025_p65;
    end else if ((~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
        output_stream_TDATA = c_fu_382_p3;
    end else begin
        output_stream_TDATA = 'bx;
    end
end

always @ (ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_reg_ppiten_pp0_it9 or exitcond6_reg_2217 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or tmp_last_V_reg_2551) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        output_stream_TLAST = tmp_last_V_reg_2551;
    end else if ((~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
        output_stream_TLAST = ap_const_lv1_0;
    end else begin
        output_stream_TLAST = 'bx;
    end
end

always @ (ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_reg_ppiten_pp0_it9 or exitcond6_reg_2217 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or ap_reg_ioackin_output_stream_TREADY) begin
    if (((~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_0 == ap_reg_ioackin_output_stream_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_0 == ap_reg_ioackin_output_stream_TREADY)))) begin
        output_stream_TVALID = ap_const_logic_1;
    end else begin
        output_stream_TVALID = ap_const_logic_0;
    end
end

always @ (stream_id_reg_221 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(stream_id_reg_221 == ap_const_lv1_0))) begin
        stream_id_phi_fu_225_p4 = ap_const_lv1_0;
    end else begin
        stream_id_phi_fu_225_p4 = stream_id_reg_221;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        v_V_ce0 = ap_const_logic_1;
    end else begin
        v_V_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        v_V_ce1 = ap_const_logic_1;
    end else begin
        v_V_ce1 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_stream_id_reg_221_pp0_it8 or ap_sig_ioackin_output_stream_TREADY or ap_reg_ppiten_pp0_it9 or stream_id_phi_fu_225_p4 or exitcond6_fu_391_p2 or exitcond6_reg_2217 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it8)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it8)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(~(ap_reg_ppstg_stream_id_reg_221_pp0_it8 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & (ap_const_lv1_0 == stream_id_phi_fu_225_p4) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_pp1_stg0_fsm_2 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_output_stream_TREADY) & (ap_const_lv1_0 == exitcond6_reg_2217) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond6_fu_391_p2))) begin
                ap_NS_fsm = ap_ST_st14_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end
        end
        ap_ST_st14_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_1648 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_183 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_58 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign c_fu_382_p3 = {{tmp_i_56_fu_376_p3}, {tmp_i_fu_370_p3}};

assign exitcond6_fu_391_p2 = (stream_id_1_reg_245 == ap_const_lv8_9D? 1'b1: 1'b0);

assign exp_V_2_fu_342_p4 = {{res_V_4_fu_338_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign exp_V_4_fu_320_p2 = ($signed(exp_V_fu_310_p4) + $signed(ap_const_lv8_E8));

assign exp_V_5_fu_352_p2 = ($signed(exp_V_2_fu_342_p4) + $signed(ap_const_lv8_E8));

assign exp_V_fu_310_p4 = {{res_V_3_fu_306_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign output_indexes_mem_addr_gep_fu_175_p3 = ap_const_lv64_1;

assign output_indexes_mem_address0 = output_indexes_mem_addr_reg_2162;

assign output_indexes_mem_address1 = tmp_84_fu_273_p1;

assign p_Result_1_fu_358_p5 = {{res_V_4_fu_338_p1[32'd31 : 32'd31]}, {exp_V_5_fu_352_p2}, {res_V_4_fu_338_p1[32'd22 : 32'd0]}};

assign p_Result_s_fu_326_p5 = {{res_V_3_fu_306_p1[32'd31 : 32'd31]}, {exp_V_4_fu_320_p2}, {res_V_3_fu_306_p1[32'd22 : 32'd0]}};

assign res_V_3_fu_306_p1 = grp_fu_267_p1;

assign res_V_4_fu_338_p1 = grp_fu_270_p1;

assign stream_id_2_fu_397_p2 = (stream_id_1_reg_245 + ap_const_lv8_1);

assign tmp_100_fu_644_p3 = firings_V_read[tmp_115_8_fu_632_p2];

assign tmp_101_fu_669_p3 = firings_V_read[tmp_115_9_fu_657_p2];

assign tmp_102_fu_694_p3 = firings_V_read[tmp_115_10_fu_682_p2];

assign tmp_103_fu_719_p3 = firings_V_read[tmp_115_11_fu_707_p2];

assign tmp_104_fu_744_p3 = firings_V_read[tmp_115_12_fu_732_p2];

assign tmp_105_fu_769_p3 = firings_V_read[tmp_115_13_fu_757_p2];

assign tmp_106_fu_798_p3 = firings_V_read[tmp_115_14_cast2_fu_788_p1];

assign tmp_107_fu_823_p3 = firings_V_read[tmp_115_15_fu_811_p2];

assign tmp_108_fu_848_p3 = firings_V_read[tmp_115_16_fu_836_p2];

assign tmp_109_fu_873_p3 = firings_V_read[tmp_115_17_fu_861_p2];

assign tmp_110_fu_898_p3 = firings_V_read[tmp_115_18_fu_886_p2];

assign tmp_111_fu_923_p3 = firings_V_read[tmp_115_19_fu_911_p2];

assign tmp_112_10_fu_688_p2 = (tmp_115_10_fu_682_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_11_fu_713_p2 = (tmp_115_11_fu_707_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_12_fu_738_p2 = (tmp_115_12_fu_732_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_13_fu_763_p2 = (tmp_115_13_fu_757_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_14_fu_792_p2 = (tmp_115_14_fu_782_p2 < ap_const_lv14_2710? 1'b1: 1'b0);

assign tmp_112_15_fu_817_p2 = (tmp_115_15_fu_811_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_16_fu_842_p2 = (tmp_115_16_fu_836_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_17_fu_867_p2 = (tmp_115_17_fu_861_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_18_fu_892_p2 = (tmp_115_18_fu_886_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_19_fu_917_p2 = (tmp_115_19_fu_911_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_1_fu_430_p2 = (tmp_115_s_fu_420_p2 < ap_const_lv14_2710? 1'b1: 1'b0);

assign tmp_112_20_fu_942_p2 = (tmp_115_20_fu_936_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_21_fu_967_p2 = (tmp_115_21_fu_961_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_22_fu_992_p2 = (tmp_115_22_fu_986_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_23_fu_1017_p2 = (tmp_115_23_fu_1011_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_24_fu_1042_p2 = (tmp_115_24_fu_1036_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_25_fu_1067_p2 = (tmp_115_25_fu_1061_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_26_fu_1092_p2 = (tmp_115_26_fu_1086_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_27_fu_1117_p2 = (tmp_115_27_fu_1111_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_28_fu_1142_p2 = (tmp_115_28_fu_1136_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_29_fu_1167_p2 = (tmp_115_29_fu_1161_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_2_fu_455_p2 = (tmp_115_1_fu_449_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_30_fu_1196_p2 = (tmp_115_30_fu_1186_p2 < ap_const_lv14_2710? 1'b1: 1'b0);

assign tmp_112_31_fu_1221_p2 = (tmp_115_31_fu_1215_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_32_fu_1246_p2 = (tmp_115_32_fu_1240_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_33_fu_1271_p2 = (tmp_115_33_fu_1265_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_34_fu_1296_p2 = (tmp_115_34_fu_1290_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_35_fu_1321_p2 = (tmp_115_35_fu_1315_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_36_fu_1346_p2 = (tmp_115_36_fu_1340_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_37_fu_1371_p2 = (tmp_115_37_fu_1365_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_38_fu_1396_p2 = (tmp_115_38_fu_1390_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_39_fu_1421_p2 = (tmp_115_39_fu_1415_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_3_fu_484_p2 = (tmp_115_2_fu_474_p2 < ap_const_lv14_2710? 1'b1: 1'b0);

assign tmp_112_40_fu_1446_p2 = (tmp_115_40_fu_1440_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_41_fu_1471_p2 = (tmp_115_41_fu_1465_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_42_fu_1496_p2 = (tmp_115_42_fu_1490_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_43_fu_1521_p2 = (tmp_115_43_fu_1515_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_44_fu_1546_p2 = (tmp_115_44_fu_1540_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_45_fu_1571_p2 = (tmp_115_45_fu_1565_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_46_fu_1596_p2 = (tmp_115_46_fu_1590_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_47_fu_1621_p2 = (tmp_115_47_fu_1615_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_48_fu_1646_p2 = (tmp_115_48_fu_1640_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_49_fu_1671_p2 = (tmp_115_49_fu_1665_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_4_fu_509_p2 = (tmp_115_3_fu_503_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_50_fu_1696_p2 = (tmp_115_50_fu_1690_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_51_fu_1721_p2 = (tmp_115_51_fu_1715_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_52_fu_1746_p2 = (tmp_115_52_fu_1740_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_53_fu_1771_p2 = (tmp_115_53_fu_1765_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_54_fu_1796_p2 = (tmp_115_54_fu_1790_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_55_fu_1821_p2 = (tmp_115_55_fu_1815_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_56_fu_1846_p2 = (tmp_115_56_fu_1840_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_57_fu_1871_p2 = (tmp_115_57_fu_1865_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_58_fu_1896_p2 = (tmp_115_58_fu_1890_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_59_fu_1921_p2 = (tmp_115_59_fu_1915_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_5_fu_534_p2 = (tmp_115_4_fu_528_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_60_fu_1946_p2 = (tmp_115_60_fu_1940_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_61_fu_1971_p2 = (tmp_115_61_fu_1965_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_62_fu_1996_p2 = (tmp_115_62_fu_1990_p2 < ap_const_lv14_2710? 1'b1: 1'b0);

assign tmp_112_6_fu_559_p2 = (tmp_115_5_fu_553_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_7_fu_588_p2 = (tmp_115_6_fu_578_p2 < ap_const_lv14_2710? 1'b1: 1'b0);

assign tmp_112_8_fu_613_p2 = (tmp_115_7_fu_607_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_9_fu_638_p2 = (tmp_115_8_fu_632_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_112_fu_948_p3 = firings_V_read[tmp_115_20_fu_936_p2];

assign tmp_112_s_fu_663_p2 = (tmp_115_9_fu_657_p2 < ap_const_lv15_2710? 1'b1: 1'b0);

assign tmp_113_fu_973_p3 = firings_V_read[tmp_115_21_fu_961_p2];

assign tmp_114_10_fu_701_p2 = (tmp_112_10_fu_688_p2 & tmp_102_fu_694_p3);

assign tmp_114_11_fu_726_p2 = (tmp_112_11_fu_713_p2 & tmp_103_fu_719_p3);

assign tmp_114_12_fu_751_p2 = (tmp_112_12_fu_738_p2 & tmp_104_fu_744_p3);

assign tmp_114_13_fu_776_p2 = (tmp_112_13_fu_763_p2 & tmp_105_fu_769_p3);

assign tmp_114_14_fu_805_p2 = (tmp_112_14_fu_792_p2 & tmp_106_fu_798_p3);

assign tmp_114_15_fu_830_p2 = (tmp_112_15_fu_817_p2 & tmp_107_fu_823_p3);

assign tmp_114_16_fu_855_p2 = (tmp_112_16_fu_842_p2 & tmp_108_fu_848_p3);

assign tmp_114_17_fu_880_p2 = (tmp_112_17_fu_867_p2 & tmp_109_fu_873_p3);

assign tmp_114_18_fu_905_p2 = (tmp_112_18_fu_892_p2 & tmp_110_fu_898_p3);

assign tmp_114_19_fu_930_p2 = (tmp_112_19_fu_917_p2 & tmp_111_fu_923_p3);

assign tmp_114_1_fu_443_p2 = (tmp_112_1_fu_430_p2 & tmp_92_fu_436_p3);

assign tmp_114_20_fu_955_p2 = (tmp_112_20_fu_942_p2 & tmp_112_fu_948_p3);

assign tmp_114_21_fu_980_p2 = (tmp_112_21_fu_967_p2 & tmp_113_fu_973_p3);

assign tmp_114_22_fu_1005_p2 = (tmp_112_22_fu_992_p2 & tmp_114_fu_998_p3);

assign tmp_114_23_fu_1030_p2 = (tmp_112_23_fu_1017_p2 & tmp_115_fu_1023_p3);

assign tmp_114_24_fu_1055_p2 = (tmp_112_24_fu_1042_p2 & tmp_116_fu_1048_p3);

assign tmp_114_25_fu_1080_p2 = (tmp_112_25_fu_1067_p2 & tmp_117_fu_1073_p3);

assign tmp_114_26_fu_1105_p2 = (tmp_112_26_fu_1092_p2 & tmp_118_fu_1098_p3);

assign tmp_114_27_fu_1130_p2 = (tmp_112_27_fu_1117_p2 & tmp_119_fu_1123_p3);

assign tmp_114_28_fu_1155_p2 = (tmp_112_28_fu_1142_p2 & tmp_120_fu_1148_p3);

assign tmp_114_29_fu_1180_p2 = (tmp_112_29_fu_1167_p2 & tmp_121_fu_1173_p3);

assign tmp_114_2_fu_468_p2 = (tmp_112_2_fu_455_p2 & tmp_93_fu_461_p3);

assign tmp_114_30_fu_1209_p2 = (tmp_112_30_fu_1196_p2 & tmp_122_fu_1202_p3);

assign tmp_114_31_fu_1234_p2 = (tmp_112_31_fu_1221_p2 & tmp_123_fu_1227_p3);

assign tmp_114_32_fu_1259_p2 = (tmp_112_32_fu_1246_p2 & tmp_124_fu_1252_p3);

assign tmp_114_33_fu_1284_p2 = (tmp_112_33_fu_1271_p2 & tmp_125_fu_1277_p3);

assign tmp_114_34_fu_1309_p2 = (tmp_112_34_fu_1296_p2 & tmp_126_fu_1302_p3);

assign tmp_114_35_fu_1334_p2 = (tmp_112_35_fu_1321_p2 & tmp_127_fu_1327_p3);

assign tmp_114_36_fu_1359_p2 = (tmp_112_36_fu_1346_p2 & tmp_128_fu_1352_p3);

assign tmp_114_37_fu_1384_p2 = (tmp_112_37_fu_1371_p2 & tmp_129_fu_1377_p3);

assign tmp_114_38_fu_1409_p2 = (tmp_112_38_fu_1396_p2 & tmp_130_fu_1402_p3);

assign tmp_114_39_fu_1434_p2 = (tmp_112_39_fu_1421_p2 & tmp_131_fu_1427_p3);

assign tmp_114_3_fu_497_p2 = (tmp_112_3_fu_484_p2 & tmp_94_fu_490_p3);

assign tmp_114_40_fu_1459_p2 = (tmp_112_40_fu_1446_p2 & tmp_132_fu_1452_p3);

assign tmp_114_41_fu_1484_p2 = (tmp_112_41_fu_1471_p2 & tmp_133_fu_1477_p3);

assign tmp_114_42_fu_1509_p2 = (tmp_112_42_fu_1496_p2 & tmp_134_fu_1502_p3);

assign tmp_114_43_fu_1534_p2 = (tmp_112_43_fu_1521_p2 & tmp_135_fu_1527_p3);

assign tmp_114_44_fu_1559_p2 = (tmp_112_44_fu_1546_p2 & tmp_136_fu_1552_p3);

assign tmp_114_45_fu_1584_p2 = (tmp_112_45_fu_1571_p2 & tmp_137_fu_1577_p3);

assign tmp_114_46_fu_1609_p2 = (tmp_112_46_fu_1596_p2 & tmp_138_fu_1602_p3);

assign tmp_114_47_fu_1634_p2 = (tmp_112_47_fu_1621_p2 & tmp_139_fu_1627_p3);

assign tmp_114_48_fu_1659_p2 = (tmp_112_48_fu_1646_p2 & tmp_140_fu_1652_p3);

assign tmp_114_49_fu_1684_p2 = (tmp_112_49_fu_1671_p2 & tmp_141_fu_1677_p3);

assign tmp_114_4_fu_522_p2 = (tmp_112_4_fu_509_p2 & tmp_95_fu_515_p3);

assign tmp_114_50_fu_1709_p2 = (tmp_112_50_fu_1696_p2 & tmp_142_fu_1702_p3);

assign tmp_114_51_fu_1734_p2 = (tmp_112_51_fu_1721_p2 & tmp_143_fu_1727_p3);

assign tmp_114_52_fu_1759_p2 = (tmp_112_52_fu_1746_p2 & tmp_144_fu_1752_p3);

assign tmp_114_53_fu_1784_p2 = (tmp_112_53_fu_1771_p2 & tmp_145_fu_1777_p3);

assign tmp_114_54_fu_1809_p2 = (tmp_112_54_fu_1796_p2 & tmp_146_fu_1802_p3);

assign tmp_114_55_fu_1834_p2 = (tmp_112_55_fu_1821_p2 & tmp_147_fu_1827_p3);

assign tmp_114_56_fu_1859_p2 = (tmp_112_56_fu_1846_p2 & tmp_148_fu_1852_p3);

assign tmp_114_57_fu_1884_p2 = (tmp_112_57_fu_1871_p2 & tmp_149_fu_1877_p3);

assign tmp_114_58_fu_1909_p2 = (tmp_112_58_fu_1896_p2 & tmp_150_fu_1902_p3);

assign tmp_114_59_fu_1934_p2 = (tmp_112_59_fu_1921_p2 & tmp_151_fu_1927_p3);

assign tmp_114_5_fu_547_p2 = (tmp_112_5_fu_534_p2 & tmp_96_fu_540_p3);

assign tmp_114_60_fu_1959_p2 = (tmp_112_60_fu_1946_p2 & tmp_153_fu_1952_p3);

assign tmp_114_61_fu_1984_p2 = (tmp_112_61_fu_1971_p2 & tmp_154_fu_1977_p3);

assign tmp_114_62_fu_2013_p2 = (tmp_112_62_fu_1996_p2 & tmp_155_fu_2006_p3);

assign tmp_114_6_fu_572_p2 = (tmp_112_6_fu_559_p2 & tmp_97_fu_565_p3);

assign tmp_114_7_fu_601_p2 = (tmp_112_7_fu_588_p2 & tmp_98_fu_594_p3);

assign tmp_114_8_fu_626_p2 = (tmp_112_8_fu_613_p2 & tmp_99_fu_619_p3);

assign tmp_114_9_fu_651_p2 = (tmp_112_9_fu_638_p2 & tmp_100_fu_644_p3);

assign tmp_114_fu_998_p3 = firings_V_read[tmp_115_22_fu_986_p2];

assign tmp_114_s_fu_676_p2 = (tmp_112_s_fu_663_p2 & tmp_101_fu_669_p3);

assign tmp_115_10_fu_682_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_4);

assign tmp_115_11_fu_707_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_5);

assign tmp_115_12_fu_732_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_6);

assign tmp_115_13_fu_757_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_7);

assign tmp_115_14_cast2_fu_788_p1 = tmp_115_14_fu_782_p2;

assign tmp_115_14_fu_782_p2 = (x_1_reg_256 | ap_const_lv14_F);

assign tmp_115_15_fu_811_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_1);

assign tmp_115_16_fu_836_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_2);

assign tmp_115_17_fu_861_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_3);

assign tmp_115_18_fu_886_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_4);

assign tmp_115_19_fu_911_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_5);

assign tmp_115_1_fu_449_p2 = (tmp_115_cast5_fu_426_p1 + ap_const_lv15_1);

assign tmp_115_20_fu_936_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_6);

assign tmp_115_21_fu_961_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_7);

assign tmp_115_22_fu_986_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_8);

assign tmp_115_23_fu_1011_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_9);

assign tmp_115_24_fu_1036_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_A);

assign tmp_115_25_fu_1061_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_B);

assign tmp_115_26_fu_1086_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_C);

assign tmp_115_27_fu_1111_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_D);

assign tmp_115_28_fu_1136_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_E);

assign tmp_115_29_fu_1161_p2 = (tmp_115_14_cast2_fu_788_p1 + ap_const_lv15_F);

assign tmp_115_2_cast4_fu_480_p1 = tmp_115_2_fu_474_p2;

assign tmp_115_2_fu_474_p2 = (x_1_reg_256 | ap_const_lv14_3);

assign tmp_115_30_cast1_fu_1192_p1 = tmp_115_30_fu_1186_p2;

assign tmp_115_30_fu_1186_p2 = (x_1_reg_256 | ap_const_lv14_1F);

assign tmp_115_31_fu_1215_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1);

assign tmp_115_32_fu_1240_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_2);

assign tmp_115_33_fu_1265_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_3);

assign tmp_115_34_fu_1290_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_4);

assign tmp_115_35_fu_1315_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_5);

assign tmp_115_36_fu_1340_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_6);

assign tmp_115_37_fu_1365_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_7);

assign tmp_115_38_fu_1390_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_8);

assign tmp_115_39_fu_1415_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_9);

assign tmp_115_3_fu_503_p2 = (tmp_115_2_cast4_fu_480_p1 + ap_const_lv15_1);

assign tmp_115_40_fu_1440_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_A);

assign tmp_115_41_fu_1465_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_B);

assign tmp_115_42_fu_1490_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_C);

assign tmp_115_43_fu_1515_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_D);

assign tmp_115_44_fu_1540_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_E);

assign tmp_115_45_fu_1565_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_F);

assign tmp_115_46_fu_1590_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_10);

assign tmp_115_47_fu_1615_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_11);

assign tmp_115_48_fu_1640_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_12);

assign tmp_115_49_fu_1665_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_13);

assign tmp_115_4_fu_528_p2 = (tmp_115_2_cast4_fu_480_p1 + ap_const_lv15_2);

assign tmp_115_50_fu_1690_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_14);

assign tmp_115_51_fu_1715_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_15);

assign tmp_115_52_fu_1740_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_16);

assign tmp_115_53_fu_1765_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_17);

assign tmp_115_54_fu_1790_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_18);

assign tmp_115_55_fu_1815_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_19);

assign tmp_115_56_fu_1840_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1A);

assign tmp_115_57_fu_1865_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1B);

assign tmp_115_58_fu_1890_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1C);

assign tmp_115_59_fu_1915_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1D);

assign tmp_115_5_fu_553_p2 = (tmp_115_2_cast4_fu_480_p1 + ap_const_lv15_3);

assign tmp_115_60_fu_1940_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1E);

assign tmp_115_61_fu_1965_p2 = (tmp_115_30_cast1_fu_1192_p1 + ap_const_lv15_1F);

assign tmp_115_62_fu_1990_p2 = (x_1_reg_256 | ap_const_lv14_3F);

assign tmp_115_6_cast3_fu_584_p1 = tmp_115_6_fu_578_p2;

assign tmp_115_6_fu_578_p2 = (x_1_reg_256 | ap_const_lv14_7);

assign tmp_115_7_fu_607_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_1);

assign tmp_115_8_fu_632_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_2);

assign tmp_115_9_fu_657_p2 = (tmp_115_6_cast3_fu_584_p1 + ap_const_lv15_3);

assign tmp_115_cast5_fu_426_p1 = tmp_115_s_fu_420_p2;

assign tmp_115_fu_1023_p3 = firings_V_read[tmp_115_23_fu_1011_p2];

assign tmp_115_s_fu_420_p2 = (x_1_reg_256 | ap_const_lv14_1);

assign tmp_116_fu_1048_p3 = firings_V_read[tmp_115_24_fu_1036_p2];

assign tmp_117_fu_1073_p3 = firings_V_read[tmp_115_25_fu_1061_p2];

assign tmp_118_fu_1098_p3 = firings_V_read[tmp_115_26_fu_1086_p2];

assign tmp_119_fu_1123_p3 = firings_V_read[tmp_115_27_fu_1111_p2];

assign tmp_120_fu_1148_p3 = firings_V_read[tmp_115_28_fu_1136_p2];

assign tmp_121_fu_1173_p3 = firings_V_read[tmp_115_29_fu_1161_p2];

assign tmp_122_fu_1202_p3 = firings_V_read[tmp_115_30_cast1_fu_1192_p1];

assign tmp_123_fu_1227_p3 = firings_V_read[tmp_115_31_fu_1215_p2];

assign tmp_124_fu_1252_p3 = firings_V_read[tmp_115_32_fu_1240_p2];

assign tmp_125_fu_1277_p3 = firings_V_read[tmp_115_33_fu_1265_p2];

assign tmp_126_fu_1302_p3 = firings_V_read[tmp_115_34_fu_1290_p2];

assign tmp_127_fu_1327_p3 = firings_V_read[tmp_115_35_fu_1315_p2];

assign tmp_128_fu_1352_p3 = firings_V_read[tmp_115_36_fu_1340_p2];

assign tmp_129_fu_1377_p3 = firings_V_read[tmp_115_37_fu_1365_p2];

assign tmp_130_fu_1402_p3 = firings_V_read[tmp_115_38_fu_1390_p2];

assign tmp_131_fu_1427_p3 = firings_V_read[tmp_115_39_fu_1415_p2];

assign tmp_132_fu_1452_p3 = firings_V_read[tmp_115_40_fu_1440_p2];

assign tmp_133_fu_1477_p3 = firings_V_read[tmp_115_41_fu_1465_p2];

assign tmp_134_fu_1502_p3 = firings_V_read[tmp_115_42_fu_1490_p2];

assign tmp_135_fu_1527_p3 = firings_V_read[tmp_115_43_fu_1515_p2];

assign tmp_136_fu_1552_p3 = firings_V_read[tmp_115_44_fu_1540_p2];

assign tmp_137_fu_1577_p3 = firings_V_read[tmp_115_45_fu_1565_p2];

assign tmp_138_fu_1602_p3 = firings_V_read[tmp_115_46_fu_1590_p2];

assign tmp_139_fu_1627_p3 = firings_V_read[tmp_115_47_fu_1615_p2];

assign tmp_140_fu_1652_p3 = firings_V_read[tmp_115_48_fu_1640_p2];

assign tmp_141_fu_1677_p3 = firings_V_read[tmp_115_49_fu_1665_p2];

assign tmp_142_fu_1702_p3 = firings_V_read[tmp_115_50_fu_1690_p2];

assign tmp_143_fu_1727_p3 = firings_V_read[tmp_115_51_fu_1715_p2];

assign tmp_144_fu_1752_p3 = firings_V_read[tmp_115_52_fu_1740_p2];

assign tmp_145_fu_1777_p3 = firings_V_read[tmp_115_53_fu_1765_p2];

assign tmp_146_fu_1802_p3 = firings_V_read[tmp_115_54_fu_1790_p2];

assign tmp_147_fu_1827_p3 = firings_V_read[tmp_115_55_fu_1815_p2];

assign tmp_148_fu_1852_p3 = firings_V_read[tmp_115_56_fu_1840_p2];

assign tmp_149_fu_1877_p3 = firings_V_read[tmp_115_57_fu_1865_p2];

assign tmp_150_fu_1902_p3 = firings_V_read[tmp_115_58_fu_1890_p2];

assign tmp_151_fu_1927_p3 = firings_V_read[tmp_115_59_fu_1915_p2];

assign tmp_153_fu_1952_p3 = firings_V_read[tmp_115_60_fu_1940_p2];

assign tmp_154_fu_1977_p3 = firings_V_read[tmp_115_61_fu_1965_p2];

assign tmp_155_fu_2006_p3 = firings_V_read[tmp_89_fu_2002_p1];

assign tmp_82_fu_284_p1 = output_indexes_mem_q0;

assign tmp_83_fu_294_p2 = (v_V_q0 == ap_const_lv32_0? 1'b1: 1'b0);

assign tmp_84_fu_273_p1 = x_reg_234;

assign tmp_85_fu_289_p1 = output_indexes_mem_q1;

assign tmp_86_fu_300_p2 = (v_V_q1 == ap_const_lv32_0? 1'b1: 1'b0);

assign tmp_88_fu_409_p1 = x_1_reg_256;

assign tmp_89_fu_2002_p1 = tmp_115_62_fu_1990_p2;

assign tmp_92_fu_436_p3 = firings_V_read[tmp_115_cast5_fu_426_p1];

assign tmp_93_fu_461_p3 = firings_V_read[tmp_115_1_fu_449_p2];

assign tmp_94_fu_490_p3 = firings_V_read[tmp_115_2_cast4_fu_480_p1];

assign tmp_95_fu_515_p3 = firings_V_read[tmp_115_3_fu_503_p2];

assign tmp_96_fu_540_p3 = firings_V_read[tmp_115_4_fu_528_p2];

assign tmp_97_fu_565_p3 = firings_V_read[tmp_115_5_fu_553_p2];

assign tmp_98_fu_594_p3 = firings_V_read[tmp_115_6_cast3_fu_584_p1];

assign tmp_99_fu_619_p3 = firings_V_read[tmp_115_7_fu_607_p2];

assign tmp_data_4_fu_2025_p65 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_114_62_reg_2546}, {tmp_114_61_reg_2541}}, {tmp_114_60_reg_2536}}, {tmp_114_59_reg_2531}}, {tmp_114_58_reg_2526}}, {tmp_114_57_reg_2521}}, {tmp_114_56_reg_2516}}, {tmp_114_55_reg_2511}}, {tmp_114_54_reg_2506}}, {tmp_114_53_reg_2501}}, {tmp_114_52_reg_2496}}, {tmp_114_51_reg_2491}}, {tmp_114_50_reg_2486}}, {tmp_114_49_reg_2481}}, {tmp_114_48_reg_2476}}, {tmp_114_47_reg_2471}}, {tmp_114_46_reg_2466}}, {tmp_114_45_reg_2461}}, {tmp_114_44_reg_2456}}, {tmp_114_43_reg_2451}}, {tmp_114_42_reg_2446}}, {tmp_114_41_reg_2441}}, {tmp_114_40_reg_2436}}, {tmp_114_39_reg_2431}}, {tmp_114_38_reg_2426}}, {tmp_114_37_reg_2421}}, {tmp_114_36_reg_2416}}, {tmp_114_35_reg_2411}}, {tmp_114_34_reg_2406}}, {tmp_114_33_reg_2401}}, {tmp_114_32_reg_2396}}, {tmp_114_31_reg_2391}}, {tmp_114_30_reg_2386}}, {tmp_114_29_reg_2381}}, {tmp_114_28_reg_2376}}, {tmp_114_27_reg_2371}}, {tmp_114_26_reg_2366}}, {tmp_114_25_reg_2361}}, {tmp_114_24_reg_2356}}, {tmp_114_23_reg_2351}}, {tmp_114_22_reg_2346}}, {tmp_114_21_reg_2341}}, {tmp_114_20_reg_2336}}, {tmp_114_19_reg_2331}}, {tmp_114_18_reg_2326}}, {tmp_114_17_reg_2321}}, {tmp_114_16_reg_2316}}, {tmp_114_15_reg_2311}}, {tmp_114_14_reg_2306}}, {tmp_114_13_reg_2301}}, {tmp_114_12_reg_2296}}, {tmp_114_11_reg_2291}}, {tmp_114_10_reg_2286}}, {tmp_114_s_reg_2281}}, {tmp_114_9_reg_2276}}, {tmp_114_8_reg_2271}}, {tmp_114_7_reg_2266}}, {tmp_114_6_reg_2261}}, {tmp_114_5_reg_2256}}, {tmp_114_4_reg_2251}}, {tmp_114_3_reg_2246}}, {tmp_114_2_reg_2241}}, {tmp_114_1_reg_2236}}, {tmp_reg_2231}};

assign tmp_fu_413_p3 = firings_V_read[tmp_88_fu_409_p1];

assign tmp_i_56_fu_376_p3 = ((ap_reg_ppstg_tmp_86_reg_2202_pp0_it8[0:0] === 1'b1) ? ap_const_lv32_0 : p_Result_1_reg_2212);

assign tmp_i_fu_370_p3 = ((ap_reg_ppstg_tmp_83_reg_2192_pp0_it8[0:0] === 1'b1) ? ap_const_lv32_0 : p_Result_s_reg_2207);

assign tmp_last_V_fu_2019_p2 = (stream_id_1_reg_245 > ap_const_lv8_9B? 1'b1: 1'b0);

assign v_V_address0 = tmp_82_fu_284_p1;

assign v_V_address1 = tmp_85_fu_289_p1;

assign x_2_fu_278_p2 = (x_reg_234 ^ ap_const_lv2_2);

assign x_3_fu_403_p2 = (x_1_reg_256 + ap_const_lv14_40);
always @ (posedge ap_clk) begin
    output_indexes_mem_addr_reg_2162[7:0] <= 8'b00000001;
end



endmodule //hls_snn_izikevich_axis_cp_output_to_stream

