// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_snn_izikevich_hls_snn_process_step (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_input_address0,
        p_input_ce0,
        p_input_q0,
        input_stream0_TDATA,
        input_stream0_TVALID,
        input_stream0_TREADY,
        input_stream0_TLAST,
        input_stream1_TDATA,
        input_stream1_TVALID,
        input_stream1_TREADY,
        input_stream1_TLAST,
        input_stream2_TDATA,
        input_stream2_TVALID,
        input_stream2_TREADY,
        input_stream2_TLAST,
        input_stream3_TDATA,
        input_stream3_TVALID,
        input_stream3_TREADY,
        input_stream3_TLAST,
        neuron_type_mem_V_address0,
        neuron_type_mem_V_ce0,
        neuron_type_mem_V_q0,
        v_mem_address0,
        v_mem_ce0,
        v_mem_we0,
        v_mem_d0,
        v_mem_q0,
        u_mem_address0,
        u_mem_ce0,
        u_mem_we0,
        u_mem_d0,
        u_mem_q0,
        firings_mem_V_address0,
        firings_mem_V_ce0,
        firings_mem_V_we0,
        firings_mem_V_d0,
        firings_mem_V_q0
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_st3_fsm_2 = 4'b100;
parameter    ap_ST_st4_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] p_input_address0;
output   p_input_ce0;
input  [31:0] p_input_q0;
input  [63:0] input_stream0_TDATA;
input   input_stream0_TVALID;
output   input_stream0_TREADY;
input  [0:0] input_stream0_TLAST;
input  [63:0] input_stream1_TDATA;
input   input_stream1_TVALID;
output   input_stream1_TREADY;
input  [0:0] input_stream1_TLAST;
input  [63:0] input_stream2_TDATA;
input   input_stream2_TVALID;
output   input_stream2_TREADY;
input  [0:0] input_stream2_TLAST;
input  [63:0] input_stream3_TDATA;
input   input_stream3_TVALID;
output   input_stream3_TREADY;
input  [0:0] input_stream3_TLAST;
output  [7:0] neuron_type_mem_V_address0;
output   neuron_type_mem_V_ce0;
input  [169:0] neuron_type_mem_V_q0;
output  [14:0] v_mem_address0;
output   v_mem_ce0;
output   v_mem_we0;
output  [31:0] v_mem_d0;
input  [31:0] v_mem_q0;
output  [14:0] u_mem_address0;
output   u_mem_ce0;
output   u_mem_we0;
output  [31:0] u_mem_d0;
input  [31:0] u_mem_q0;
output  [8:0] firings_mem_V_address0;
output   firings_mem_V_ce0;
output   firings_mem_V_we0;
output  [63:0] firings_mem_V_d0;
input  [63:0] firings_mem_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_input_ce0;
reg neuron_type_mem_V_ce0;
reg v_mem_ce0;
reg v_mem_we0;
reg u_mem_ce0;
reg u_mem_we0;
reg firings_mem_V_ce0;
reg firings_mem_V_we0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [7:0] p_mem_V_address0;
reg    p_mem_V_ce0;
reg    p_mem_V_we0;
wire   [0:0] p_mem_V_d0;
wire   [0:0] p_mem_V_q0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_ap_idle;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_ap_ready;
wire   [7:0] grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_address0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_ce0;
wire   [0:0] grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_q0;
wire   [7:0] grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_address0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_ce0;
wire   [169:0] grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_q0;
wire   [14:0] grp_hls_snn_izikevich_snn_process_step_fu_90_v_address0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_v_ce0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_v_we0;
wire   [31:0] grp_hls_snn_izikevich_snn_process_step_fu_90_v_d0;
wire   [31:0] grp_hls_snn_izikevich_snn_process_step_fu_90_v_q0;
wire   [14:0] grp_hls_snn_izikevich_snn_process_step_fu_90_u_address0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_u_ce0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_u_we0;
wire   [31:0] grp_hls_snn_izikevich_snn_process_step_fu_90_u_d0;
wire   [31:0] grp_hls_snn_izikevich_snn_process_step_fu_90_u_q0;
wire   [63:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TDATA;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TVALID;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TLAST;
wire   [63:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TDATA;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TVALID;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TLAST;
wire   [63:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TDATA;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TVALID;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TLAST;
wire   [63:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TDATA;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TVALID;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TREADY;
wire   [0:0] grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TLAST;
wire   [8:0] grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_address0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_ce0;
wire    grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_we0;
wire   [63:0] grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_d0;
wire   [63:0] grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_q0;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_done;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_idle;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_ready;
wire   [2:0] grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_address0;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_ce0;
wire   [31:0] grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_q0;
wire   [7:0] grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_address0;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_ce0;
wire    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_we0;
wire   [0:0] grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_d0;
reg    grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_151;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_158;
reg    grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_608;
reg   [3:0] ap_NS_fsm;


hls_snn_izikevich_hls_snn_process_step_p_mem_V #(
    .DataWidth( 1 ),
    .AddressRange( 170 ),
    .AddressWidth( 8 ))
p_mem_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_mem_V_address0 ),
    .ce0( p_mem_V_ce0 ),
    .we0( p_mem_V_we0 ),
    .d0( p_mem_V_d0 ),
    .q0( p_mem_V_q0 )
);

hls_snn_izikevich_snn_process_step grp_hls_snn_izikevich_snn_process_step_fu_90(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start ),
    .ap_done( grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done ),
    .ap_idle( grp_hls_snn_izikevich_snn_process_step_fu_90_ap_idle ),
    .ap_ready( grp_hls_snn_izikevich_snn_process_step_fu_90_ap_ready ),
    .p_V_address0( grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_address0 ),
    .p_V_ce0( grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_ce0 ),
    .p_V_q0( grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_q0 ),
    .neuron_type_V_address0( grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_address0 ),
    .neuron_type_V_ce0( grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_ce0 ),
    .neuron_type_V_q0( grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_q0 ),
    .v_address0( grp_hls_snn_izikevich_snn_process_step_fu_90_v_address0 ),
    .v_ce0( grp_hls_snn_izikevich_snn_process_step_fu_90_v_ce0 ),
    .v_we0( grp_hls_snn_izikevich_snn_process_step_fu_90_v_we0 ),
    .v_d0( grp_hls_snn_izikevich_snn_process_step_fu_90_v_d0 ),
    .v_q0( grp_hls_snn_izikevich_snn_process_step_fu_90_v_q0 ),
    .u_address0( grp_hls_snn_izikevich_snn_process_step_fu_90_u_address0 ),
    .u_ce0( grp_hls_snn_izikevich_snn_process_step_fu_90_u_ce0 ),
    .u_we0( grp_hls_snn_izikevich_snn_process_step_fu_90_u_we0 ),
    .u_d0( grp_hls_snn_izikevich_snn_process_step_fu_90_u_d0 ),
    .u_q0( grp_hls_snn_izikevich_snn_process_step_fu_90_u_q0 ),
    .input_stream0_TDATA( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TDATA ),
    .input_stream0_TVALID( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TVALID ),
    .input_stream0_TREADY( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TREADY ),
    .input_stream0_TLAST( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TLAST ),
    .input_stream1_TDATA( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TDATA ),
    .input_stream1_TVALID( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TVALID ),
    .input_stream1_TREADY( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TREADY ),
    .input_stream1_TLAST( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TLAST ),
    .input_stream2_TDATA( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TDATA ),
    .input_stream2_TVALID( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TVALID ),
    .input_stream2_TREADY( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TREADY ),
    .input_stream2_TLAST( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TLAST ),
    .input_stream3_TDATA( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TDATA ),
    .input_stream3_TVALID( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TVALID ),
    .input_stream3_TREADY( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TREADY ),
    .input_stream3_TLAST( grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TLAST ),
    .firings_V_address0( grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_address0 ),
    .firings_V_ce0( grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_ce0 ),
    .firings_V_we0( grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_we0 ),
    .firings_V_d0( grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_d0 ),
    .firings_V_q0( grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_q0 )
);

hls_snn_izikevich_axis_cp_inputs_to_mem grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start ),
    .ap_done( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_done ),
    .ap_idle( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_idle ),
    .ap_ready( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_ready ),
    .p_input_address0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_address0 ),
    .p_input_ce0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_ce0 ),
    .p_input_q0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_q0 ),
    .p_mem_V_address0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_address0 ),
    .p_mem_V_ce0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_ce0 ),
    .p_mem_V_we0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_we0 ),
    .p_mem_V_d0( grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_d0 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_ready)) begin
            grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_hls_snn_izikevich_snn_process_step_fu_90_ap_ready)) begin
            grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_608) begin
    if (ap_sig_bdd_608) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_151) begin
    if (ap_sig_bdd_151) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_158) begin
    if (ap_sig_bdd_158) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_ce0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        firings_mem_V_ce0 = grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_ce0;
    end else begin
        firings_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_we0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        firings_mem_V_we0 = grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_we0;
    end else begin
        firings_mem_V_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_ce0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        neuron_type_mem_V_ce0 = grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_ce0;
    end else begin
        neuron_type_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_ce0 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_input_ce0 = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_ce0;
    end else begin
        p_input_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_address0 or grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_address0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_mem_V_address0 = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_mem_V_address0 = grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_address0;
    end else begin
        p_mem_V_address0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_ce0 or grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_ce0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_mem_V_ce0 = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_mem_V_ce0 = grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_ce0;
    end else begin
        p_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_we0 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_mem_V_we0 = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_we0;
    end else begin
        p_mem_V_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_u_ce0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        u_mem_ce0 = grp_hls_snn_izikevich_snn_process_step_fu_90_u_ce0;
    end else begin
        u_mem_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_u_we0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        u_mem_we0 = grp_hls_snn_izikevich_snn_process_step_fu_90_u_we0;
    end else begin
        u_mem_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_v_ce0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        v_mem_ce0 = grp_hls_snn_izikevich_snn_process_step_fu_90_v_ce0;
    end else begin
        v_mem_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_snn_process_step_fu_90_v_we0 or ap_sig_cseq_ST_st4_fsm_3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        v_mem_we0 = grp_hls_snn_izikevich_snn_process_step_fu_90_v_we0;
    end else begin
        v_mem_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done or grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_done) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_logic_0 == grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(ap_const_logic_0 == grp_hls_snn_izikevich_snn_process_step_fu_90_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_151 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_158 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_608 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign firings_mem_V_address0 = grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_address0;

assign firings_mem_V_d0 = grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_d0;

assign grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_ap_start_ap_start_reg;

assign grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_q0 = p_input_q0;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start = grp_hls_snn_izikevich_snn_process_step_fu_90_ap_start_ap_start_reg;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_firings_V_q0 = firings_mem_V_q0;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TDATA = input_stream0_TDATA;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TLAST = input_stream0_TLAST;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TVALID = input_stream0_TVALID;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TDATA = input_stream1_TDATA;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TLAST = input_stream1_TLAST;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TVALID = input_stream1_TVALID;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TDATA = input_stream2_TDATA;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TLAST = input_stream2_TLAST;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TVALID = input_stream2_TVALID;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TDATA = input_stream3_TDATA;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TLAST = input_stream3_TLAST;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TVALID = input_stream3_TVALID;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_q0 = neuron_type_mem_V_q0;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_p_V_q0 = p_mem_V_q0;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_u_q0 = u_mem_q0;

assign grp_hls_snn_izikevich_snn_process_step_fu_90_v_q0 = v_mem_q0;

assign input_stream0_TREADY = grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream0_TREADY;

assign input_stream1_TREADY = grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream1_TREADY;

assign input_stream2_TREADY = grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream2_TREADY;

assign input_stream3_TREADY = grp_hls_snn_izikevich_snn_process_step_fu_90_input_stream3_TREADY;

assign neuron_type_mem_V_address0 = grp_hls_snn_izikevich_snn_process_step_fu_90_neuron_type_V_address0;

assign p_input_address0 = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_input_address0;

assign p_mem_V_d0 = grp_hls_snn_izikevich_axis_cp_inputs_to_mem_fu_162_p_mem_V_d0;

assign u_mem_address0 = grp_hls_snn_izikevich_snn_process_step_fu_90_u_address0;

assign u_mem_d0 = grp_hls_snn_izikevich_snn_process_step_fu_90_u_d0;

assign v_mem_address0 = grp_hls_snn_izikevich_snn_process_step_fu_90_v_address0;

assign v_mem_d0 = grp_hls_snn_izikevich_snn_process_step_fu_90_v_d0;


endmodule //hls_snn_izikevich_hls_snn_process_step

