// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_snn_izikevich,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.824000,HLS_SYN_LAT=378862,HLS_SYN_TPT=none,HLS_SYN_MEM=223,HLS_SYN_DSP=53,HLS_SYN_FF=30829,HLS_SYN_LUT=41239}" *)

module hls_snn_izikevich (
        ap_clk,
        ap_rst_n,
        input_stream0_TDATA,
        input_stream0_TVALID,
        input_stream0_TREADY,
        input_stream0_TLAST,
        input_stream1_TDATA,
        input_stream1_TVALID,
        input_stream1_TREADY,
        input_stream1_TLAST,
        input_stream2_TDATA,
        input_stream2_TVALID,
        input_stream2_TREADY,
        input_stream2_TLAST,
        input_stream3_TDATA,
        input_stream3_TVALID,
        input_stream3_TREADY,
        input_stream3_TLAST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_st4_fsm_3 = 5'b1000;
parameter    ap_ST_st5_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_true = 1'b1;
parameter    C_S_AXI_CONTROL_WSTRB_WIDTH = (C_S_AXI_CONTROL_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] input_stream0_TDATA;
input   input_stream0_TVALID;
output   input_stream0_TREADY;
input  [0:0] input_stream0_TLAST;
input  [63:0] input_stream1_TDATA;
input   input_stream1_TVALID;
output   input_stream1_TREADY;
input  [0:0] input_stream1_TLAST;
input  [63:0] input_stream2_TDATA;
input   input_stream2_TVALID;
output   input_stream2_TREADY;
input  [0:0] input_stream2_TLAST;
input  [63:0] input_stream3_TDATA;
input   input_stream3_TVALID;
output   input_stream3_TREADY;
input  [0:0] input_stream3_TLAST;
output  [63:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [0:0] output_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1 : 0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1 : 0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1 : 0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1 : 0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1 : 0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg input_stream0_TREADY;
reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg    ap_ready;
wire   [0:0] state_V;
wire   [2:0] p_input_address0;
reg    p_input_ce0;
wire   [31:0] p_input_q0;
wire   [0:0] output_indexes_address0;
reg    output_indexes_ce0;
wire   [31:0] output_indexes_q0;
reg   [7:0] neuron_type_mem_V_address0;
reg    neuron_type_mem_V_ce0;
reg    neuron_type_mem_V_we0;
wire   [169:0] neuron_type_mem_V_d0;
wire   [169:0] neuron_type_mem_V_q0;
reg   [31:0] output_indexes_mem_0 = 32'b00000000000000000000000000000000;
reg   [31:0] output_indexes_mem_1 = 32'b00000000000000000000000000000000;
reg   [14:0] v_mem_address0;
reg    v_mem_ce0;
reg    v_mem_we0;
reg   [31:0] v_mem_d0;
wire   [31:0] v_mem_q0;
wire   [14:0] v_mem_address1;
reg    v_mem_ce1;
wire   [31:0] v_mem_q1;
reg   [14:0] u_mem_address0;
reg    u_mem_ce0;
reg    u_mem_we0;
reg   [31:0] u_mem_d0;
wire   [31:0] u_mem_q0;
reg   [8:0] firings_mem_V_address0;
reg    firings_mem_V_ce0;
reg    firings_mem_V_we0;
wire   [63:0] firings_mem_V_d0;
wire   [63:0] firings_mem_V_q0;
wire   [0:0] ap_return;
wire    hls_snn_izikevich_control_s_axi_U_ap_dummy_ce;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_150;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_done;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_idle;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_ready;
wire   [2:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_address0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_ce0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_q0;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TDATA;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TVALID;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TREADY;
wire   [0:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TLAST;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TDATA;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TVALID;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TREADY;
wire   [0:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TLAST;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TDATA;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TVALID;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TREADY;
wire   [0:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TLAST;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TDATA;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TVALID;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TREADY;
wire   [0:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TLAST;
wire   [7:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_address0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_ce0;
wire   [169:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_q0;
wire   [14:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_address0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_ce0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_d0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_q0;
wire   [14:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_address0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_ce0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_d0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_q0;
wire   [8:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_address0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_ce0;
wire    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_we0;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_d0;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_q0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_done;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_idle;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_ready;
wire   [63:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TDATA;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TVALID;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TREADY;
wire   [0:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TLAST;
wire   [0:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_address0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_ce0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_q0;
wire   [7:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_address0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_ce0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_we0;
wire   [169:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_d0;
wire   [169:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_q0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0_ap_vld;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1_ap_vld;
wire   [14:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_address0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_ce0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_d0;
wire   [14:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_address0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_ce0;
wire    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_we0;
wire   [31:0] grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_d0;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_idle;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_ready;
wire   [63:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TDATA;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TVALID;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TREADY;
wire   [0:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TLAST;
wire   [14:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address0;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce0;
wire   [31:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_q0;
wire   [14:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address1;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce1;
wire   [31:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_q1;
wire   [31:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_indexes_mem_0_read;
wire   [31:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_indexes_mem_1_read;
wire   [8:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_address0;
wire    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_ce0;
wire   [63:0] grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_q0;
reg    grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start_ap_start_reg = 1'b0;
wire   [0:0] state_V_read_read_fu_122_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_263;
reg    grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_724;
reg    grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_745;
reg   [4:0] ap_NS_fsm;


hls_snn_izikevich_neuron_type_mem_V #(
    .DataWidth( 170 ),
    .AddressRange( 170 ),
    .AddressWidth( 8 ))
neuron_type_mem_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( neuron_type_mem_V_address0 ),
    .ce0( neuron_type_mem_V_ce0 ),
    .we0( neuron_type_mem_V_we0 ),
    .d0( neuron_type_mem_V_d0 ),
    .q0( neuron_type_mem_V_q0 )
);

hls_snn_izikevich_v_mem #(
    .DataWidth( 32 ),
    .AddressRange( 28900 ),
    .AddressWidth( 15 ))
v_mem_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( v_mem_address0 ),
    .ce0( v_mem_ce0 ),
    .we0( v_mem_we0 ),
    .d0( v_mem_d0 ),
    .q0( v_mem_q0 ),
    .address1( v_mem_address1 ),
    .ce1( v_mem_ce1 ),
    .q1( v_mem_q1 )
);

hls_snn_izikevich_u_mem #(
    .DataWidth( 32 ),
    .AddressRange( 28900 ),
    .AddressWidth( 15 ))
u_mem_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( u_mem_address0 ),
    .ce0( u_mem_ce0 ),
    .we0( u_mem_we0 ),
    .d0( u_mem_d0 ),
    .q0( u_mem_q0 )
);

hls_snn_izikevich_firings_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 452 ),
    .AddressWidth( 9 ))
firings_mem_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( firings_mem_V_address0 ),
    .ce0( firings_mem_V_ce0 ),
    .we0( firings_mem_V_we0 ),
    .d0( firings_mem_V_d0 ),
    .q0( firings_mem_V_q0 )
);

hls_snn_izikevich_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
hls_snn_izikevich_control_s_axi_U(
    .AWVALID( s_axi_control_AWVALID ),
    .AWREADY( s_axi_control_AWREADY ),
    .AWADDR( s_axi_control_AWADDR ),
    .WVALID( s_axi_control_WVALID ),
    .WREADY( s_axi_control_WREADY ),
    .WDATA( s_axi_control_WDATA ),
    .WSTRB( s_axi_control_WSTRB ),
    .ARVALID( s_axi_control_ARVALID ),
    .ARREADY( s_axi_control_ARREADY ),
    .ARADDR( s_axi_control_ARADDR ),
    .RVALID( s_axi_control_RVALID ),
    .RREADY( s_axi_control_RREADY ),
    .RDATA( s_axi_control_RDATA ),
    .RRESP( s_axi_control_RRESP ),
    .BVALID( s_axi_control_BVALID ),
    .BREADY( s_axi_control_BREADY ),
    .BRESP( s_axi_control_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( hls_snn_izikevich_control_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .ap_return( ap_return ),
    .state_V( state_V ),
    .p_input_address0( p_input_address0 ),
    .p_input_ce0( p_input_ce0 ),
    .p_input_q0( p_input_q0 ),
    .output_indexes_address0( output_indexes_address0 ),
    .output_indexes_ce0( output_indexes_ce0 ),
    .output_indexes_q0( output_indexes_q0 )
);

hls_snn_izikevich_hls_snn_process_step grp_hls_snn_izikevich_hls_snn_process_step_fu_128(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start ),
    .ap_done( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_done ),
    .ap_idle( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_idle ),
    .ap_ready( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_ready ),
    .p_input_address0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_address0 ),
    .p_input_ce0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_ce0 ),
    .p_input_q0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_q0 ),
    .input_stream0_TDATA( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TDATA ),
    .input_stream0_TVALID( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TVALID ),
    .input_stream0_TREADY( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TREADY ),
    .input_stream0_TLAST( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TLAST ),
    .input_stream1_TDATA( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TDATA ),
    .input_stream1_TVALID( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TVALID ),
    .input_stream1_TREADY( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TREADY ),
    .input_stream1_TLAST( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TLAST ),
    .input_stream2_TDATA( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TDATA ),
    .input_stream2_TVALID( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TVALID ),
    .input_stream2_TREADY( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TREADY ),
    .input_stream2_TLAST( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TLAST ),
    .input_stream3_TDATA( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TDATA ),
    .input_stream3_TVALID( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TVALID ),
    .input_stream3_TREADY( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TREADY ),
    .input_stream3_TLAST( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TLAST ),
    .neuron_type_mem_V_address0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_address0 ),
    .neuron_type_mem_V_ce0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_ce0 ),
    .neuron_type_mem_V_q0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_q0 ),
    .v_mem_address0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_address0 ),
    .v_mem_ce0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_ce0 ),
    .v_mem_we0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_we0 ),
    .v_mem_d0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_d0 ),
    .v_mem_q0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_q0 ),
    .u_mem_address0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_address0 ),
    .u_mem_ce0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_ce0 ),
    .u_mem_we0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_we0 ),
    .u_mem_d0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_d0 ),
    .u_mem_q0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_q0 ),
    .firings_mem_V_address0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_address0 ),
    .firings_mem_V_ce0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_ce0 ),
    .firings_mem_V_we0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_we0 ),
    .firings_mem_V_d0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_d0 ),
    .firings_mem_V_q0( grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_q0 )
);

hls_snn_izikevich_hls_snn_initialize grp_hls_snn_izikevich_hls_snn_initialize_fu_202(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start ),
    .ap_done( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_done ),
    .ap_idle( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_idle ),
    .ap_ready( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_ready ),
    .input_stream0_TDATA( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TDATA ),
    .input_stream0_TVALID( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TVALID ),
    .input_stream0_TREADY( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TREADY ),
    .input_stream0_TLAST( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TLAST ),
    .output_indexes_address0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_address0 ),
    .output_indexes_ce0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_ce0 ),
    .output_indexes_q0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_q0 ),
    .neuron_type_mem_V_address0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_address0 ),
    .neuron_type_mem_V_ce0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_ce0 ),
    .neuron_type_mem_V_we0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_we0 ),
    .neuron_type_mem_V_d0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_d0 ),
    .neuron_type_mem_V_q0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_q0 ),
    .output_indexes_mem_0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0 ),
    .output_indexes_mem_0_ap_vld( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0_ap_vld ),
    .output_indexes_mem_1( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1 ),
    .output_indexes_mem_1_ap_vld( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1_ap_vld ),
    .v_mem_address0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_address0 ),
    .v_mem_ce0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_ce0 ),
    .v_mem_we0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_we0 ),
    .v_mem_d0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_d0 ),
    .u_mem_address0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_address0 ),
    .u_mem_ce0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_ce0 ),
    .u_mem_we0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_we0 ),
    .u_mem_d0( grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_d0 )
);

hls_snn_izikevich_axis_cp_output_to_stream grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start ),
    .ap_done( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done ),
    .ap_idle( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_idle ),
    .ap_ready( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_ready ),
    .output_stream_TDATA( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TDATA ),
    .output_stream_TVALID( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TVALID ),
    .output_stream_TREADY( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TREADY ),
    .output_stream_TLAST( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TLAST ),
    .v_address0( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address0 ),
    .v_ce0( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce0 ),
    .v_q0( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_q0 ),
    .v_address1( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address1 ),
    .v_ce1( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce1 ),
    .v_q1( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_q1 ),
    .output_indexes_mem_0_read( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_indexes_mem_0_read ),
    .output_indexes_mem_1_read( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_indexes_mem_1_read ),
    .firings_mem_V_address0( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_address0 ),
    .firings_mem_V_ce0( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_ce0 ),
    .firings_mem_V_q0( grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_q0 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
            grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_ready)) begin
            grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (state_V_read_read_fu_122_p2 == ap_const_lv1_0))) begin
            grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_ready)) begin
            grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start_ap_start_reg
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & ~(state_V_read_read_fu_122_p2 == ap_const_lv1_0))) begin
            grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_ready)) begin
            grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (state_V_read_read_fu_122_p2 == ap_const_lv1_0) & (ap_const_logic_1 == grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0_ap_vld)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_logic_1 == grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0_ap_vld)))) begin
        output_indexes_mem_0 <= grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (state_V_read_read_fu_122_p2 == ap_const_lv1_0) & (ap_const_logic_1 == grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1_ap_vld)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_logic_1 == grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1_ap_vld)))) begin
        output_indexes_mem_1 <= grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_mem_1;
    end
end

always @ (grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_23) begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_724) begin
    if (ap_sig_bdd_724) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_263) begin
    if (ap_sig_bdd_263) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_150) begin
    if (ap_sig_bdd_150) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_745) begin
    if (ap_sig_bdd_745) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_address0 or grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_address0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st5_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        firings_mem_V_address0 = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        firings_mem_V_address0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_address0;
    end else begin
        firings_mem_V_address0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_ce0 or grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_ce0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st5_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        firings_mem_V_ce0 = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        firings_mem_V_ce0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_ce0;
    end else begin
        firings_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_we0 or ap_sig_cseq_ST_st3_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        firings_mem_V_we0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_we0;
    end else begin
        firings_mem_V_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TREADY or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TREADY or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        input_stream0_TREADY = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TREADY;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        input_stream0_TREADY = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TREADY;
    end else begin
        input_stream0_TREADY = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_address0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_address0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        neuron_type_mem_V_address0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        neuron_type_mem_V_address0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_address0;
    end else begin
        neuron_type_mem_V_address0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_ce0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_ce0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        neuron_type_mem_V_ce0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        neuron_type_mem_V_ce0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_ce0;
    end else begin
        neuron_type_mem_V_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_we0 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        neuron_type_mem_V_we0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_we0;
    end else begin
        neuron_type_mem_V_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_ce0 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_indexes_ce0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_ce0;
    end else begin
        output_indexes_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_ce0 or ap_sig_cseq_ST_st3_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_input_ce0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_ce0;
    end else begin
        p_input_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_address0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_address0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        u_mem_address0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        u_mem_address0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_address0;
    end else begin
        u_mem_address0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_ce0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_ce0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        u_mem_ce0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        u_mem_ce0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_ce0;
    end else begin
        u_mem_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_d0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_d0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        u_mem_d0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_d0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        u_mem_d0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_d0;
    end else begin
        u_mem_d0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_we0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_we0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        u_mem_we0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_u_mem_we0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        u_mem_we0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_we0;
    end else begin
        u_mem_we0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_address0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_address0 or grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st5_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        v_mem_address0 = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        v_mem_address0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        v_mem_address0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_address0;
    end else begin
        v_mem_address0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_ce0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_ce0 or grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st5_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        v_mem_ce0 = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        v_mem_ce0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        v_mem_ce0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_ce0;
    end else begin
        v_mem_ce0 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce1 or ap_sig_cseq_ST_st5_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        v_mem_ce1 = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_ce1;
    end else begin
        v_mem_ce1 = ap_const_logic_0;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_d0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_d0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        v_mem_d0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_d0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        v_mem_d0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_d0;
    end else begin
        v_mem_d0 = 'bx;
    end
end

always @ (grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_we0 or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_we0 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        v_mem_we0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_v_mem_we0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        v_mem_we0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_we0;
    end else begin
        v_mem_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_done or grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_done or grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done or state_V_read_read_fu_122_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if ((~(ap_start == ap_const_logic_0) & ~(state_V_read_read_fu_122_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else if ((~(ap_start == ap_const_logic_0) & (state_V_read_read_fu_122_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_logic_0 == grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_done)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_logic_0 == grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_done)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_logic_0 == grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ap_return = ap_const_lv1_1;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_150 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_263 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_724 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_745 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

assign firings_mem_V_d0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_d0;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_ap_start_ap_start_reg;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_firings_mem_V_q0 = firings_mem_V_q0;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_indexes_mem_0_read = output_indexes_mem_0;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_indexes_mem_1_read = output_indexes_mem_1;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TREADY = output_stream_TREADY;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_q0 = v_mem_q0;

assign grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_q1 = v_mem_q1;

assign grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_ap_start_ap_start_reg;

assign grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TDATA = input_stream0_TDATA;

assign grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TLAST = input_stream0_TLAST;

assign grp_hls_snn_izikevich_hls_snn_initialize_fu_202_input_stream0_TVALID = input_stream0_TVALID;

assign grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_q0 = neuron_type_mem_V_q0;

assign grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_q0 = output_indexes_q0;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_ap_start_ap_start_reg;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_firings_mem_V_q0 = firings_mem_V_q0;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TDATA = input_stream0_TDATA;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TLAST = input_stream0_TLAST;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream0_TVALID = input_stream0_TVALID;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TDATA = input_stream1_TDATA;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TLAST = input_stream1_TLAST;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TVALID = input_stream1_TVALID;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TDATA = input_stream2_TDATA;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TLAST = input_stream2_TLAST;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TVALID = input_stream2_TVALID;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TDATA = input_stream3_TDATA;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TLAST = input_stream3_TLAST;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TVALID = input_stream3_TVALID;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_neuron_type_mem_V_q0 = neuron_type_mem_V_q0;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_q0 = p_input_q0;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_u_mem_q0 = u_mem_q0;

assign grp_hls_snn_izikevich_hls_snn_process_step_fu_128_v_mem_q0 = v_mem_q0;

assign hls_snn_izikevich_control_s_axi_U_ap_dummy_ce = ap_const_logic_1;

assign input_stream1_TREADY = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream1_TREADY;

assign input_stream2_TREADY = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream2_TREADY;

assign input_stream3_TREADY = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_input_stream3_TREADY;

assign neuron_type_mem_V_d0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_neuron_type_mem_V_d0;

assign output_indexes_address0 = grp_hls_snn_izikevich_hls_snn_initialize_fu_202_output_indexes_address0;

assign output_stream_TDATA = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TDATA;

assign output_stream_TLAST = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TLAST;

assign output_stream_TVALID = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_output_stream_TVALID;

assign p_input_address0 = grp_hls_snn_izikevich_hls_snn_process_step_fu_128_p_input_address0;

assign state_V_read_read_fu_122_p2 = state_V;

assign v_mem_address1 = grp_hls_snn_izikevich_axis_cp_output_to_stream_fu_222_v_address1;


endmodule //hls_snn_izikevich

